import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { PinProtectedAction } from '../src/components/PinProtectedAction';
import { Account, ViewMode, AccountClassification } from '../types';
import { supabase } from '../src/utils/supabaseClient';
import {
  Plus,
  Landmark,
  CreditCard,
  MoreVertical,
  TrendingUp,
  Trash2,
  AlertTriangle,
  Power,
  ChevronDown,
  ChevronRight,
  PowerOff
} from 'lucide-react';
import { getDueDayForDisplay, ordinalSuffix } from '../src/utils/billingCycles';
import { useTheme } from '../src/contexts/ThemeContext';

interface AccountsProps {
  accounts: Account[];
  onAdd: (a: Account) => Promise<void>;
  onDelete?: (id: string) => Promise<void>;
  onEdit?: (a: Account) => Promise<void>;
  onDeactivate?: (id: string, when: { month: number; year: number } | 'now') => Promise<void>;
  loading?: boolean;
  error?: string | null;
}

const monthNames = [
  'January','February','March','April','May','June','July','August','September','October','November','December'
];

/** Prefix for fake-date strings used to store billing day numbers in the DB DATE column.
 *  Storing as "2000-01-DD" lets us reuse the existing DATE column without a schema migration.
 *  Existing code extracts the day via `new Date(billingDate).getDate()`, which works for both
 *  real dates (e.g. "2026-01-12") and these fake-date strings (e.g. "2000-01-12").
 */
const FAKE_DATE_PREFIX = '2000-01-';

const Accounts: React.FC<AccountsProps> = ({ accounts = [], onAdd, onDelete, onEdit, onDeactivate, loading = false, error = null }) => {
  const { getAccentClasses } = useTheme();
  const [viewMode, setViewMode] = useState<ViewMode>('card');
  const [showModal, setShowModal] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [confirmModal, setConfirmModal] = useState<{
    show: boolean;
    title: string;
    message: string;
    onConfirm: () => void;
  }>({
    show: false,
    title: '',
    message: '',
    onConfirm: () => {},
  });

  const [formData, setFormData] = useState({
    bank: '',
    classification: 'Checking' as AccountClassification,
    balance: '',
    type: 'Debit' as 'Debit' | 'Credit',
    creditLimit: '',
    billingDate: '',
    dueDate: ''
  });

  // menu open state per-account (id or null)
  const [openMenuId, setOpenMenuId] = useState<string | null>(null);
  
  // collapsible sections state
  const [isDebitOpen, setIsDebitOpen] = useState(true);
  const [isCreditOpen, setIsCreditOpen] = useState(true);

  // deactivate dialog state
  const [deactivateState, setDeactivateState] = useState<{
    show: boolean;
    accountId?: string | null;
    month: number;
    year: number;
  }>({
    show: false,
    accountId: null,
    month: 0,
    year: 0
  });
  
  const [deleteFailedModal, setDeleteFailedModal] = useState<{
    show: boolean;
    accountId: string;
  }>({ show: false, accountId: '' });

  useEffect(() => {
    const now = new Date();
    const nextMonthIndex = (now.getMonth() + 1) % 12; // 0-11
    const defaultYear = now.getFullYear() + (now.getMonth() === 11 ? 1 : 0);
    setDeactivateState(s => ({ ...s, month: nextMonthIndex, year: defaultYear }));
  }, []);

  // Keep a minimal accounts list (id + bank) in localStorage so the transactions page can build payment method options.
  useEffect(() => {
    if (typeof window === 'undefined') return;
    try {
      const minimal = accounts.map(a => ({ id: a.id, bank: a.bank }));
      localStorage.setItem('accounts_list', JSON.stringify(minimal));
      // Also write per-account meta for convenience
      minimal.forEach(m => localStorage.setItem(`account_meta_${m.id}`, JSON.stringify({ bank: m.bank })));
    } catch (_) {}
  }, [accounts]);

  const formatCurrency = (val: number | undefined) => {
    const n = val ?? 0;
    return new Intl.NumberFormat('en-PH', {
      style: 'currency',
      currency: 'PHP',
      minimumFractionDigits: 2,
      maximumFractionDigits: 2
    }).format(n);
  };

  const resetForm = () => {
    setFormData({ bank: '', classification: 'Checking', balance: '', type: 'Debit', creditLimit: '', billingDate: '', dueDate: '' });
    setEditingId(null);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isSubmitting) return;

    setIsSubmitting(true);
    try {
      const created: Account = {
        id: editingId ?? '', // ID will be generated by Supabase for new accounts
        bank: formData.bank,
        classification: formData.classification,
        balance: parseFloat(formData.balance || '0'),
        openingBalance: parseFloat(formData.balance || '0'), // Persisted to opening_balance DB column
        type: formData.type,
        creditLimit: formData.type === 'Credit' ? (formData.creditLimit ? parseFloat(formData.creditLimit) : 0) : undefined,
        billingDate: formData.type === 'Credit' ? (formData.billingDate ? `${FAKE_DATE_PREFIX}${formData.billingDate.padStart(2, '0')}` : undefined) : undefined,
        dueDate: formData.type === 'Credit' ? (formData.dueDate ? `${FAKE_DATE_PREFIX}${formData.dueDate.padStart(2, '0')}` : undefined) : undefined
      };

      if (editingId) {
        await onEdit?.(created);
      } else {
        await onAdd(created);
      }

      resetForm();
      setShowModal(false);
    } catch (error) {
      console.error('Failed to save account:', error);
      // Keep modal open so user can retry
    } finally {
      setIsSubmitting(false);
    }
  };

  const openAddModal = () => {
    resetForm();
    setShowModal(true);
  };

  const openEditModal = (acc: Account) => {
    setEditingId(acc.id);
    setFormData({
      bank: acc.bank,
      classification: acc.classification,
      balance: (acc.openingBalance ?? 0).toFixed(2), // Use opening balance seed, not calculated running balance
      type: acc.type,
      creditLimit: acc.creditLimit ? acc.creditLimit.toFixed(2) : '',
      billingDate: acc.billingDate ? String(new Date(acc.billingDate).getDate()) : '',
      dueDate: acc.dueDate ? String(new Date(acc.dueDate).getDate()) : ''
    });
    setShowModal(true);
  };

  const handleDeleteTrigger = (id: string, bank: string) => {
    setConfirmModal({
      show: true,
      title: 'Remove Account',
      message: `Are you sure you want to permanently remove the account: "${bank}"? This might affect your recorded balances.`,
      onConfirm: async () => {
          try {
            await onDelete?.(id);
            setConfirmModal(p => ({ ...p, show: false }));
          } catch (err) {
            setConfirmModal(p => ({ ...p, show: false }));
            setDeleteFailedModal({ show: true, accountId: id });
          }
      }
    });
  };

  const openDeactivateDialog = (id: string) => {
    setDeactivateState(s => ({
      ...s,
      show: true,
      accountId: id
    }));
  };

  const confirmDeactivateNow = async () => {
    if (!deactivateState.accountId) return;
    await onDeactivate?.(deactivateState.accountId, 'now');
    setDeactivateState({ show: false, accountId: null, month: 0, year: 0 });
  };

  const confirmDeactivateScheduled = async () => {
    if (!deactivateState.accountId) return;
    await onDeactivate?.(deactivateState.accountId, { month: deactivateState.month, year: deactivateState.year });
    setDeactivateState({ show: false, accountId: null, month: 0, year: 0 });
  };

  const renderAccount = (acc: Account) => {
    const isCredit = acc.type === 'Credit';
    const creditLimit = acc.creditLimit ?? 0;
    // If credit limit is 0 or undefined, treat progress as 0 to avoid division by zero
    const usedPercent = creditLimit > 0 ? Math.min(100, Math.round((acc.balance / creditLimit) * 100)) : 0;
    const usedPercentSafe = usedPercent < 0 ? 0 : usedPercent;
    const isActive = (acc as any).isActive !== false;
    const deactivationDate = (acc as any).deactivationDate;

    return (
      <div key={acc.id} className="bg-white dark:bg-gray-900 p-6 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-800 hover:border-indigo-200 dark:hover:border-indigo-400 transition-all relative group overflow-hidden">
        <div className={`absolute top-0 right-0 w-24 h-24 -mr-8 -mt-8 rounded-full opacity-5 ${isCredit ? 'bg-purple-500' : 'bg-green-500'}`}></div>
        
        <div className="flex justify-between items-start mb-6">
          <div className={`p-3 rounded-xl transition-colors ${isCredit ? 'bg-purple-50 dark:bg-purple-900/30 text-purple-600 dark:text-purple-400' : 'bg-green-50 dark:bg-green-900/30 text-green-600 dark:text-green-400'}`}>
            {isCredit ? <CreditCard className="w-6 h-6" /> : <Landmark className="w-6 h-6" />}
          </div>

          <div className="relative">
            <button
              onClick={(e) => { e.stopPropagation(); setOpenMenuId(openMenuId === acc.id ? null : acc.id); }}
              className="p-2 text-gray-400 dark:text-gray-500 hover:text-gray-600 dark:hover:text-gray-300 rounded-xl transition-all"
              aria-label="More options"
            >
              <MoreVertical className="w-4 h-4" />
            </button>

            {openMenuId === acc.id && (
              <div 
                className="absolute right-0 mt-2 w-44 bg-white dark:bg-gray-900 rounded-xl shadow-lg border border-gray-100 dark:border-gray-800 z-50 transition-colors"
                onClick={(e) => e.stopPropagation()}
              >
                <button
                  onClick={(e) => { e.stopPropagation(); setOpenMenuId(null); openEditModal(acc); }}
                  className="w-full text-left px-4 py-3 hover:bg-gray-50 dark:hover:bg-gray-800 text-gray-700 dark:text-gray-300 flex items-center space-x-3 text-sm transition-colors"
                >
                  <span>Edit</span>
                </button>
            {isActive && (
              <button
                onClick={(e) => { e.stopPropagation(); setOpenMenuId(null); openDeactivateDialog(acc.id); }}
                className="w-full text-left px-4 py-3 hover:bg-gray-50 dark:hover:bg-gray-800 text-gray-700 dark:text-gray-300 flex items-center space-x-3 text-sm transition-colors"
              >
                <span>Deactivate</span>
              </button>
            )}
                <button
                  onClick={(e) => { e.stopPropagation(); setOpenMenuId(null); handleDeleteTrigger(acc.id, acc.bank); }}
                  className="w-full text-left px-4 py-3 hover:bg-red-50 dark:hover:bg-red-900/20 flex items-center space-x-3 text-sm text-red-600 dark:text-red-400 transition-colors"
                >
                  <span>Delete</span>
                </button>
              </div>
            )}
          </div>
        </div>

        <div className="mb-4">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-lg font-bold text-gray-900 dark:text-gray-100 leading-tight transition-colors">{acc.bank}</h3>
              <p className="text-xs text-gray-400 dark:text-gray-500 font-medium uppercase tracking-wider transition-colors">{acc.classification}</p>
            </div>
          <span className={`text-[10px] font-bold px-2 py-0.5 rounded uppercase flex items-center gap-1 transition-colors ${isActive ? 'bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400' : 'bg-gray-100 dark:bg-gray-800 text-gray-500 dark:text-gray-400'}`}>
            {isActive ? <><Power className="w-3 h-3" />Active</> : <><PowerOff className="w-3 h-3" />Inactive</>}
          </span>
          </div>
        </div>

        {/* Credit-specific UI: credit limit + progress bar shown above current balance */}
        {isCredit && (
          <div className="mb-4">
            <div className="flex items-center justify-between mb-2">
              <p className="text-xs text-gray-400 dark:text-gray-500 font-medium transition-colors">Credit Limit</p>
              <p className="text-sm font-semibold text-gray-800 dark:text-gray-200 transition-colors">{formatCurrency(creditLimit)}</p>
            </div>

            <div className="w-full bg-gray-100 dark:bg-gray-800 rounded-full h-3 overflow-hidden transition-colors">
              <div
                className={`h-3 rounded-full ${usedPercentSafe >= 90 ? 'bg-red-500' : 'bg-purple-600'}`}
                style={{ width: `${usedPercentSafe}%`, transition: 'width 300ms ease' }}
                aria-valuenow={usedPercentSafe}
                aria-valuemin={0}
                aria-valuemax={100}
                role="progressbar"
              />
            </div>

            <div className="flex items-center justify-between mt-2 text-[11px] text-gray-500 dark:text-gray-400 transition-colors">
              <span>Used</span>
              <span className="font-medium">{usedPercentSafe}%</span>
            </div>
          </div>
        )}

        <div className="space-y-4">
          <div>
            <p className="text-xs text-gray-400 dark:text-gray-500 font-medium transition-colors">Balance</p>
            <p className={`text-2xl font-bold text-gray-900 dark:text-gray-100 transition-colors`}>{formatCurrency(acc.balance)}</p>
          </div>
      {isActive && deactivationDate && (
        <p className="text-xs text-orange-500 font-medium transition-colors">
          Scheduled to deactivate: {monthNames[deactivationDate.month]} {deactivationDate.year}
        </p>
      )}
          {isCredit && acc.billingDate && (
            <p className="text-xs text-gray-400 dark:text-gray-500 transition-colors">
              Statement: {new Date(acc.billingDate).getDate()}{ordinalSuffix(new Date(acc.billingDate).getDate())} each month
            </p>
          )}
          {isCredit && acc.billingDate && acc.dueDate && (
            <p className="text-xs text-gray-400 dark:text-gray-500 transition-colors">
              Due: {new Date(acc.dueDate).getDate()} days after → ~{getDueDayForDisplay(new Date(acc.billingDate).getDate(), new Date(acc.dueDate).getDate())}
            </p>
          )}
        </div>

        {/* Bottom controls: View button placed in lower-right corner */}
        <div className="mt-6 flex items-center justify-between">
          <div />{/* spacer */}
          <div className="flex items-center space-x-2">
            {isCredit && (
              <Link
                to={`/accounts/statement?account=${acc.id}`}
                onClick={(e) => e.stopPropagation()}
                className="bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-400 px-3 py-2 rounded-xl text-sm font-semibold hover:bg-purple-200 dark:hover:bg-purple-900/50 transition-colors"
                aria-label={`View ${acc.bank} statement`}
              >
                View Statement
              </Link>
            )}
            <Link
              to={`/accounts/view?account=${acc.id}`}
              onClick={(e) => e.stopPropagation()}
              className="bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-300 px-3 py-2 rounded-xl text-sm font-semibold hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors"
              aria-label={`View ${acc.bank} transactions`}
            >
              View
            </Link>
          </div>
        </div>
      </div>
    );
  };

  const debitAccounts = accounts.filter(a => a.type === 'Debit');
  const creditAccounts = accounts.filter(a => a.type === 'Credit');

  return (
    <div className="space-y-8 animate-in fade-in duration-500 pb-12" onClick={() => setOpenMenuId(null)}>
      {/* Header Banner */}
      <div className="bg-fuchsia-500 border-[4px] border-black rounded-[2.5rem] px-8 md:px-12 pt-12 pb-12 mb-8 shadow-[8px_8px_0px_0px_black] relative overflow-hidden">
        <div className="absolute top-0 right-0 w-64 h-64 bg-white/10 rounded-full -mr-20 -mt-20 blur-3xl"></div>
        <div className="relative z-10">
          <h1 className="font-['Titan_One'] text-4xl md:text-5xl uppercase tracking-tighter text-white drop-shadow-[4px_4px_0px_black]">
            Accounts
          </h1>
          <p className="font-black text-fuchsia-100 uppercase tracking-[0.3em] mt-4 text-xs md:text-sm drop-shadow-[1px_1px_0px_black]">
            Manage your bank accounts and credit cards
          </p>
        </div>
      </div>

      <div className="space-y-12">
        {/* Loading/Error States */}
        {loading && (
          <div className="text-center py-12">
            <div className="inline-block w-8 h-8 border-4 border-indigo-500 border-t-transparent rounded-full animate-spin mb-4"></div>
            <p className="text-gray-500 dark:text-gray-400">Loading accounts...</p>
          </div>
        )}

        {error && (
          <div className="bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400 p-4 rounded-xl text-sm font-medium text-center">
            {error}
          </div>
        )}

        {!loading && !error && (
          <>
            <div className="flex items-center gap-3 self-end sm:self-auto flex-wrap justify-end">
              <Link to="/transactions" className="flex items-center gap-2 bg-gray-50 dark:bg-gray-800 text-gray-700 dark:text-gray-300 px-5 py-3 rounded-xl font-bold text-sm hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors">
                <span className="hidden sm:inline">Transactions</span>
              </Link>
              <button onClick={openAddModal} className={`flex items-center gap-2 text-white px-5 py-3 rounded-xl font-bold transition-all shadow-md dark:shadow-none text-sm ${getAccentClasses('bg')} ${getAccentClasses('shadow')}`}>
                <Plus className="w-4 h-4" />
                <span className="hidden sm:inline">Add Account</span>
              </button>
            </div>

      {/* Empty State */}
      {debitAccounts.length === 0 && creditAccounts.length === 0 && (
        <div className="text-center py-12">
          <div className="inline-flex items-center justify-center w-20 h-20 rounded-full bg-gray-100 dark:bg-gray-800 mb-4 transition-colors">
            <Landmark className="w-10 h-10 text-gray-400 dark:text-gray-500 transition-colors" />
          </div>
          <h3 className="text-xl font-bold text-gray-900 dark:text-gray-100 mb-2 transition-colors">No Accounts Yet</h3>
          <p className="text-gray-500 dark:text-gray-400 mb-6 transition-colors">Get started by adding your first account</p>
          <button 
            onClick={openAddModal}
            className="inline-flex items-center space-x-2 bg-indigo-600 text-white px-6 py-3 rounded-2xl font-bold hover:bg-indigo-700 shadow-lg dark:shadow-none transition-all"
          >
            <Plus className="w-5 h-5" />
            <span>Add Your First Account</span>
          </button>
        </div>
      )}

      <section>
        <button 
          onClick={() => setIsDebitOpen(!isDebitOpen)}
          className="flex items-center space-x-2 mb-6 text-gray-700 dark:text-gray-300 hover:text-gray-900 dark:hover:text-gray-100 font-bold text-lg transition-colors"
        >
          {isDebitOpen ? <ChevronDown className="w-5 h-5" /> : <ChevronRight className="w-5 h-5" />}
          <TrendingUp className="w-5 h-5 text-green-500 dark:text-green-400 transition-colors" />
          <h3 className="text-xl font-bold text-gray-800 dark:text-gray-200 uppercase tracking-widest text-sm transition-colors">Debit & Assets ({debitAccounts.length})</h3>
        </button>
        {isDebitOpen && (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {debitAccounts.map(renderAccount)}
          </div>
        )}
      </section>

      <section>
        <button 
          onClick={() => setIsCreditOpen(!isCreditOpen)}
          className="flex items-center space-x-2 mb-6 text-gray-700 dark:text-gray-300 hover:text-gray-900 dark:hover:text-gray-100 font-bold text-lg transition-colors"
        >
          {isCreditOpen ? <ChevronDown className="w-5 h-5" /> : <ChevronRight className="w-5 h-5" />}
          <CreditCard className="w-5 h-5 text-purple-500 dark:text-purple-400 transition-colors" />
          <h3 className="text-xl font-bold text-gray-800 dark:text-gray-200 uppercase tracking-widest text-sm transition-colors">Credit & Liabilities ({creditAccounts.length})</h3>
        </button>
        {isCreditOpen && (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {creditAccounts.map(renderAccount)}
          </div>
        )}
      </section>
          </>
        )}
      </div>

      {showModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-md">
          <div className="bg-white dark:bg-gray-900 rounded-3xl w-full max-w-2xl overflow-hidden shadow-2xl flex flex-col md:flex-row transition-colors">
            <div className="bg-gray-900 dark:bg-gray-950 md:w-1/3 p-8 text-white flex flex-col justify-between transition-colors">
              <div>
                <Landmark className="w-12 h-12 mb-6 text-indigo-400" />
                <h2 className="text-2xl font-black mb-2 uppercase text-white">{editingId ? 'Edit Account' : 'Connect Account'}</h2>
              </div>
            </div>
            <form onSubmit={handleSubmit} className="p-8 flex-1 bg-white dark:bg-gray-900 space-y-6 transition-colors">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-bold text-gray-400 dark:text-gray-500 uppercase mb-1 transition-colors">Bank Name</label>
                  <input required type="text" value={formData.bank} onChange={(e) => setFormData({...formData, bank: e.target.value})} className="w-full bg-transparent text-gray-900 dark:text-gray-100 border border-gray-200 dark:border-gray-700 rounded-lg px-3 py-2 outline-none focus:border-indigo-500 transition-colors" />
                </div>
                <div>
                  <label className="block text-xs font-bold text-gray-400 dark:text-gray-500 uppercase mb-1 transition-colors">Type</label>
                  <select value={formData.type} onChange={(e) => setFormData({...formData, type: e.target.value as 'Debit' | 'Credit'})} className="w-full bg-transparent text-gray-900 dark:text-gray-100 border border-gray-200 dark:border-gray-700 rounded-lg px-3 py-2 outline-none focus:border-indigo-500 transition-colors">
                    <option value="Debit">Debit</option>
                    <option value="Credit">Credit</option>
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-bold text-gray-400 dark:text-gray-500 uppercase mb-1 transition-colors">Classification</label>
                  <select value={formData.classification} onChange={(e) => setFormData({...formData, classification: e.target.value as AccountClassification})} className="w-full bg-transparent text-gray-900 dark:text-gray-100 border border-gray-200 dark:border-gray-700 rounded-lg px-3 py-2 outline-none focus:border-indigo-500 transition-colors">
                    <option>Checking</option>
                    <option>Savings</option>
                    <option>Investment</option>
                    <option>Loan</option>
                    <option>Other</option>
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-bold text-gray-400 dark:text-gray-500 uppercase mb-1 transition-colors">Opening Balance</label>
                  <input required type="number" value={formData.balance} onChange={(e) => setFormData({...formData, balance: e.target.value})} className="w-full bg-transparent text-gray-900 dark:text-gray-100 border border-gray-200 dark:border-gray-700 rounded-lg px-3 py-2 outline-none focus:border-indigo-500 transition-colors" />
                </div>
              </div>

              {formData.type === 'Credit' && (
                <>
                  <div className="grid grid-cols-3 gap-4">
                    <div>
                      <label className="block text-xs font-bold text-gray-400 dark:text-gray-500 uppercase mb-1 transition-colors">Credit Limit</label>
                      <input type="number" value={formData.creditLimit} onChange={(e) => setFormData({...formData, creditLimit: e.target.value})} className="w-full bg-transparent text-gray-900 dark:text-gray-100 border border-gray-200 dark:border-gray-700 rounded-lg px-3 py-2 outline-none focus:border-indigo-500 transition-colors" />
                    </div>
                    <div>
                      <label className="block text-xs font-bold text-gray-400 dark:text-gray-500 uppercase mb-1 transition-colors">Statement Day <span className="normal-case font-normal text-gray-400 dark:text-gray-500">(day bill cuts)</span></label>
                      <input type="number" min="1" max="31" placeholder="e.g. 12" value={formData.billingDate} onChange={(e) => setFormData({...formData, billingDate: e.target.value})} className="w-full bg-transparent text-gray-900 dark:text-gray-100 border border-gray-200 dark:border-gray-700 rounded-lg px-3 py-2 outline-none focus:border-indigo-500 transition-colors" />
                    </div>
                    <div>
                      <label className="block text-xs font-bold text-gray-400 dark:text-gray-500 uppercase mb-1 transition-colors">Days to Pay <span className="normal-case font-normal text-gray-400 dark:text-gray-500">(grace period)</span></label>
                      <input type="number" min="1" max="60" placeholder="e.g. 21" value={formData.dueDate} onChange={(e) => setFormData({...formData, dueDate: e.target.value})} className="w-full bg-transparent text-gray-900 dark:text-gray-100 border border-gray-200 dark:border-gray-700 rounded-lg px-3 py-2 outline-none focus:border-indigo-500 transition-colors" />
                    </div>
                  </div>
                  {formData.billingDate && formData.dueDate && (() => {
                    const statementDay = parseInt(formData.billingDate);
                    const daysToPay = parseInt(formData.dueDate);
                    if (isNaN(statementDay) || isNaN(daysToPay)) return null;
                    const displayStr = getDueDayForDisplay(statementDay, daysToPay);
                    return (
                      <p className="text-xs text-purple-600 dark:text-purple-400 mt-2 transition-colors">
                        📅 Statement cuts on the {statementDay}{ordinalSuffix(statementDay)} · Due ~{displayStr}
                      </p>
                    );
                  })()}
                </>
              )}

              <div className="flex space-x-4 pt-4">
                <button type="button" onClick={() => { setShowModal(false); resetForm(); }} className="flex-1 bg-gray-100 dark:bg-gray-800 py-4 rounded-xl font-bold text-gray-500 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors">Cancel</button>
                <button type="submit" className="flex-1 bg-indigo-600 text-white py-4 rounded-xl font-bold hover:bg-indigo-700 transition-colors">{editingId ? 'Save Changes' : 'Add Account'}</button>
              </div>
            </form>
          </div>
        </div>
      )}

      {deactivateState.show && (
        <DeactivateDialog
          accountId={deactivateState.accountId!}
          accounts={accounts}
          month={deactivateState.month}
          year={deactivateState.year}
          onChangeMonth={(m) => setDeactivateState(s => ({ ...s, month: m }))}
          onChangeYear={(y) => setDeactivateState(s => ({ ...s, year: y }))}
          onClose={() => setDeactivateState({ show: false, accountId: null, month: 0, year: 0 })}
          onNow={() => confirmDeactivateNow()}
          onSchedule={() => confirmDeactivateScheduled()}
        />
      )}

      {deleteFailedModal.show && (
        <div className="fixed inset-0 z-[200] flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm animate-in fade-in">
          <div className="bg-white dark:bg-gray-900 rounded-[2.5rem] w-full max-w-sm p-10 shadow-2xl animate-in zoom-in-95 flex flex-col items-center text-center transition-colors">
            <div className="w-16 h-16 bg-orange-50 dark:bg-orange-900/20 text-orange-600 dark:text-orange-400 rounded-3xl flex items-center justify-center mb-6 transition-colors">
              <AlertTriangle className="w-8 h-8" />
            </div>
            <h3 className="text-xl font-black text-gray-900 dark:text-gray-100 mb-2 uppercase tracking-tight transition-colors">Cannot Delete</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400 mb-8 font-medium leading-relaxed transition-colors">This account cannot be deleted because it has attached transactions, wallets, or schedules. Would you like to deactivate it instead?</p>
            <div className="flex flex-col w-full space-y-3">
              <button onClick={() => { 
                setDeleteFailedModal({ show: false, accountId: '' }); 
                openDeactivateDialog(deleteFailedModal.accountId); 
              }} className="w-full bg-indigo-600 text-white py-4 rounded-2xl font-black uppercase tracking-widest text-[10px] hover:bg-indigo-700 transition-all shadow-lg shadow-indigo-100 dark:shadow-none">
                Deactivate Instead
              </button>
              <button onClick={() => setDeleteFailedModal({ show: false, accountId: '' })} className="w-full bg-gray-100 dark:bg-gray-800 text-gray-500 dark:text-gray-300 py-4 rounded-2xl font-black uppercase tracking-widest text-[10px] hover:bg-gray-200 dark:hover:bg-gray-700 transition-all">
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}

      {confirmModal.show && <ConfirmDialog {...confirmModal} onClose={() => setConfirmModal(p => ({ ...p, show: false }))} />}
    </div>
  );
};

const DeactivateDialog: React.FC<{
  accountId: string;
  accounts: Account[];
  month: number;
  year: number;
  onChangeMonth: (m: number) => void;
  onChangeYear: (y: number) => void;
  onClose: () => void;
  onNow: () => Promise<void>;
  onSchedule: () => Promise<void>;
}> = ({ accountId, accounts, month, year, onChangeMonth, onChangeYear, onClose, onNow, onSchedule }) => {
  const now = new Date();
  const currentYear = now.getFullYear();
  const years = Array.from({ length: 6 }, (_, i) => currentYear + i);

  const [linkedWallets, setLinkedWallets] = useState<any[]>([]);
  const [reassignAccountId, setReassignAccountId] = useState('');
  const [isLoadingWallets, setIsLoadingWallets] = useState(true);
  const [isProcessing, setIsProcessing] = useState(false);

  useEffect(() => {
    const fetchWallets = async () => {
      setIsLoadingWallets(true);
      try {
        const isTestMode = localStorage.getItem('test_environment_enabled') === 'true';
        const tableName = isTestMode ? 'wallets_test' : 'wallets';
        const { data, error } = await supabase.from(tableName).select('*').eq('account_id', accountId);
        if (!error && data) setLinkedWallets(data);
      } catch (e) {
        console.error(e);
      } finally {
        setIsLoadingWallets(false);
      }
    };
    if (accountId) fetchWallets();
  }, [accountId]);

  const handleAction = async (action: 'now' | 'schedule') => {
    if (linkedWallets.length > 0 && !reassignAccountId) {
      alert('Please select a new account for the linked wallets before proceeding.');
      return;
    }
    setIsProcessing(true);
    try {
      if (linkedWallets.length > 0 && reassignAccountId) {
        const isTestMode = localStorage.getItem('test_environment_enabled') === 'true';
        const tableName = isTestMode ? 'wallets_test' : 'wallets';
        for (const w of linkedWallets) {
          await supabase.from(tableName).update({ account_id: reassignAccountId }).eq('id', w.id);
        }
      }
      if (action === 'now') await onNow();
      else await onSchedule();
    } catch (e) {
      console.error(e);
      alert('Failed to process deactivation.');
    } finally {
      setIsProcessing(false);
    }
  };

  const eligibleAccounts = accounts.filter(a => a.id !== accountId && a.type !== 'Credit');

  return (
    <div className="fixed inset-0 z-[200] flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm animate-in fade-in">
      <div className="bg-white dark:bg-gray-900 rounded-[2.5rem] w-full max-w-md p-8 shadow-2xl animate-in zoom-in-95 transition-colors">
        <h3 className="text-xl font-black text-gray-900 dark:text-gray-100 mb-2 uppercase tracking-tight transition-colors">Deactivate Account</h3>
        <p className="text-sm text-gray-500 dark:text-gray-400 mb-6 font-medium leading-relaxed transition-colors">Choose whether to deactivate the account now or schedule deactivation for a later month and year.</p>

        {!isLoadingWallets && linkedWallets.length > 0 && (
          <div className="mb-6 bg-orange-50 border border-orange-200 rounded-xl p-4 transition-colors">
            <div className="flex items-center space-x-2 mb-2">
              <AlertTriangle className="w-4 h-4 text-orange-500" />
              <p className="text-xs font-bold text-orange-800">Wallets Linked</p>
            </div>
            <p className="text-xs text-orange-700 mb-3">
              This account has {linkedWallets.length} linked wallet(s). Please select a new debit account to reassign them to.
            </p>
            <select 
              value={reassignAccountId} 
              onChange={(e) => setReassignAccountId(e.target.value)} 
              className="w-full bg-white border border-orange-200 rounded-lg px-3 py-2 text-sm font-bold text-gray-700 outline-none focus:ring-2 focus:ring-orange-400 transition-colors"
            >
              <option value="">-- Select New Account --</option>
              {eligibleAccounts.map(a => (
                <option key={a.id} value={a.id}>{a.bank} ({a.classification})</option>
              ))}
            </select>
            {eligibleAccounts.length === 0 && (
              <p className="text-[10px] text-red-500 mt-1 font-bold">No other debit accounts available to receive wallets.</p>
            )}
          </div>
        )}

        <div className="space-y-4">
          <PinProtectedAction
            featureId="account_deactivations"
            onVerified={() => handleAction('now')}
            actionLabel="Deactivate Account"
          >
            <button onClick={(e) => e.preventDefault()} disabled={isProcessing} className="w-full bg-red-600 text-white py-3 rounded-2xl font-black uppercase tracking-widest hover:bg-red-700 transition-all disabled:opacity-50">
              {isProcessing ? 'Processing...' : 'Deactivate Now'}
            </button>
          </PinProtectedAction>

          <div className="p-4 border border-gray-100 dark:border-gray-800 rounded-xl transition-colors">
            <p className="text-sm text-gray-600 dark:text-gray-300 mb-2 font-medium transition-colors">Deactivate on</p>
            <div className="flex space-x-2">
              <select value={month} onChange={(e) => onChangeMonth(parseInt(e.target.value, 10))} className="flex-1 bg-transparent text-gray-900 dark:text-gray-100 border border-gray-200 dark:border-gray-700 rounded-lg px-3 py-2 outline-none focus:border-indigo-500 transition-colors">
                {monthNames.map((mName, idx) => <option key={idx} value={idx}>{mName}</option>)}
              </select>
              <select value={year} onChange={(e) => onChangeYear(parseInt(e.target.value, 10))} className="w-28 bg-transparent text-gray-900 dark:text-gray-100 border border-gray-200 dark:border-gray-700 rounded-lg px-3 py-2 outline-none focus:border-indigo-500 transition-colors">
                {years.map(y => <option key={y} value={y}>{y}</option>)}
              </select>
            </div>
            <div className="mt-4">
            <PinProtectedAction
              featureId="account_deactivations"
              onVerified={() => handleAction('schedule')}
              actionLabel="Schedule Deactivation"
            >
              <button onClick={(e) => e.preventDefault()} disabled={isProcessing} className="w-full bg-indigo-600 text-white py-2 rounded-xl font-bold hover:bg-indigo-700 transition-colors disabled:opacity-50">{isProcessing ? 'Processing...' : 'Schedule Deactivation'}</button>
            </PinProtectedAction>
            </div>
          </div>

          <button onClick={onClose} disabled={isProcessing} className="w-full bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-300 py-3 rounded-2xl font-black uppercase tracking-widest hover:bg-gray-200 dark:hover:bg-gray-700 transition-all disabled:opacity-50">
            Cancel
          </button>
        </div>
      </div>
    </div>
  );
};

const ConfirmDialog: React.FC<{ show: boolean; title: string; message: string; onConfirm: () => void; onClose: () => void }> = ({ title, message, onConfirm, onClose }) => (
  <div className="fixed inset-0 z-[200] flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm animate-in fade-in">
    <div className="bg-white dark:bg-gray-900 rounded-[2.5rem] w-full max-w-sm p-10 shadow-2xl animate-in zoom-in-95 flex flex-col items-center text-center transition-colors">
      <div className="w-16 h-16 bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400 rounded-3xl flex items-center justify-center mb-6 transition-colors">
        <AlertTriangle className="w-8 h-8" />
      </div>
      <h3 className="text-xl font-black text-gray-900 dark:text-gray-100 mb-2 uppercase tracking-tight transition-colors">{title}</h3>
      <p className="text-sm text-gray-500 dark:text-gray-400 mb-8 font-medium leading-relaxed transition-colors">{message}</p>
      <div className="flex flex-col w-full space-y-3">
        <PinProtectedAction
          featureId="account_deletions"
          onVerified={onConfirm}
          actionLabel="Delete Account"
        >
          <button onClick={(e) => e.preventDefault()} className="w-full bg-red-600 text-white py-4 rounded-2xl font-black uppercase tracking-widest text-[10px] hover:bg-red-700 transition-all shadow-lg shadow-red-100 dark:shadow-none">
            Proceed
          </button>
        </PinProtectedAction>
        <button onClick={onClose} className="w-full bg-gray-100 dark:bg-gray-800 text-gray-500 dark:text-gray-300 py-4 rounded-2xl font-black uppercase tracking-widest text-[10px] hover:bg-gray-200 dark:hover:bg-gray-700 transition-all">
          Cancel
        </button>
      </div>
    </div>
  </div>
);

export default Accounts;
