import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { PinProtectedAction } from '../src/components/PinProtectedAction';
import { Account, AccountClassification } from '../types';
import { supabase } from '../src/utils/supabaseClient';
import {
  Plus,
  CreditCard,
  MoreVertical,
  TrendingUp,
  WalletCards,
  AlertTriangle,
  ChevronDown,
  ChevronRight,
  ArrowUpRight,
  Sparkles
} from 'lucide-react';
import { getDueDayForDisplay, ordinalSuffix } from '../src/utils/billingCycles';
import { useTheme } from '../src/contexts/ThemeContext';
import { PageHeader } from '../src/components/PageHeader';

interface AccountsProps {
  accounts: Account[];
  onAdd: (a: Account) => Promise<void>;
  onDelete?: (id: string) => Promise<void>;
  onEdit?: (a: Account) => Promise<void>;
  onDeactivate?: (id: string, when: { month: number; year: number } | 'now') => Promise<void>;
  loading?: boolean;
  error?: string | null;
}

const monthNames = [
  'January','February','March','April','May','June','July','August','September','October','November','December'
];

/** Prefix for fake-date strings used to store billing day numbers in the DB DATE column.
 *  Storing as "2000-01-DD" lets us reuse the existing DATE column without a schema migration.
 *  Existing code extracts the day via `new Date(billingDate).getDate()`, which works for both
 *  real dates (e.g. "2026-01-12") and these fake-date strings (e.g. "2000-01-12").
 */
const FAKE_DATE_PREFIX = '2000-01-';

const Accounts: React.FC<AccountsProps> = ({ accounts, onAdd, onDelete, onEdit, onDeactivate, loading = false, error = null }) => {
  const { getAccentClasses } = useTheme();
  const [showModal, setShowModal] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [confirmModal, setConfirmModal] = useState<{
    show: boolean;
    title: string;
    message: string;
    onConfirm: () => void;
  }>({
    show: false,
    title: '',
    message: '',
    onConfirm: () => {},
  });

  const [formData, setFormData] = useState({
    bank: '',
    classification: 'Checking' as AccountClassification,
    balance: '',
    type: 'Debit' as 'Debit' | 'Credit',
    creditLimit: '',
    billingDate: '',
    dueDate: ''
  });

  // menu open state per-account (id or null)
  const [openMenuId, setOpenMenuId] = useState<string | null>(null);
  
  // collapsible sections state
  const [isDebitOpen, setIsDebitOpen] = useState(true);
  const [isCreditOpen, setIsCreditOpen] = useState(true);

  // deactivate dialog state
  const [deactivateState, setDeactivateState] = useState<{
    show: boolean;
    accountId?: string | null;
    month: number;
    year: number;
  }>({
    show: false,
    accountId: null,
    month: 0,
    year: 0
  });
  
  const [deleteFailedModal, setDeleteFailedModal] = useState<{
    show: boolean;
    accountId: string;
  }>({ show: false, accountId: '' });

  useEffect(() => {
    const now = new Date();
    const nextMonthIndex = (now.getMonth() + 1) % 12; // 0-11
    const defaultYear = now.getFullYear() + (now.getMonth() === 11 ? 1 : 0);
    setDeactivateState(s => ({ ...s, month: nextMonthIndex, year: defaultYear }));
  }, []);

  // Keep a minimal accounts list (id + bank) in localStorage so the transactions page can build payment method options.
  useEffect(() => {
    if (typeof window === 'undefined') return;
    try {
      const minimal = accounts.map(a => ({ id: a.id, bank: a.bank }));
      localStorage.setItem('accounts_list', JSON.stringify(minimal));
      // Also write per-account meta for convenience
      minimal.forEach(m => localStorage.setItem(`account_meta_${m.id}`, JSON.stringify({ bank: m.bank })));
    } catch (_) {}
  }, [accounts]);

  const formatCurrency = (val: number | undefined) => {
    const n = val ?? 0;
    return new Intl.NumberFormat('en-PH', {
      style: 'currency',
      currency: 'PHP',
      minimumFractionDigits: 2,
      maximumFractionDigits: 2
    }).format(n);
  };

  const resetForm = () => {
    setFormData({ bank: '', classification: 'Checking', balance: '', type: 'Debit', creditLimit: '', billingDate: '', dueDate: '' });
    setEditingId(null);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isSubmitting) return;

    setIsSubmitting(true);
    try {
      const created: Account = {
        id: editingId ?? '', // ID will be generated by Supabase for new accounts
        bank: formData.bank,
        classification: formData.classification,
        balance: parseFloat(formData.balance || '0'),
        openingBalance: parseFloat(formData.balance || '0'), // Persisted to opening_balance DB column
        type: formData.type,
        creditLimit: formData.type === 'Credit' ? (formData.creditLimit ? parseFloat(formData.creditLimit) : 0) : undefined,
        billingDate: formData.type === 'Credit' ? (formData.billingDate ? `${FAKE_DATE_PREFIX}${formData.billingDate.padStart(2, '0')}` : undefined) : undefined,
        dueDate: formData.type === 'Credit' ? (formData.dueDate ? `${FAKE_DATE_PREFIX}${formData.dueDate.padStart(2, '0')}` : undefined) : undefined
      };

      if (editingId) {
        await onEdit?.(created);
      } else {
        await onAdd(created);
      }

      resetForm();
      setShowModal(false);
    } catch (error) {
      console.error('Failed to save account:', error);
      // Keep modal open so user can retry
    } finally {
      setIsSubmitting(false);
    }
  };

  const openAddModal = () => {
    resetForm();
    setShowModal(true);
  };

  const openEditModal = (acc: Account) => {
    setEditingId(acc.id);
    setFormData({
      bank: acc.bank,
      classification: acc.classification,
      balance: (acc.openingBalance ?? 0).toFixed(2), // Use opening balance seed, not calculated running balance
      type: acc.type,
      creditLimit: acc.creditLimit ? acc.creditLimit.toFixed(2) : '',
      billingDate: acc.billingDate ? String(new Date(acc.billingDate).getDate()) : '',
      dueDate: acc.dueDate ? String(new Date(acc.dueDate).getDate()) : ''
    });
    setShowModal(true);
  };

  const handleDeleteTrigger = (id: string, bank: string) => {
    setConfirmModal({
      show: true,
      title: 'Remove Account',
      message: `Are you sure you want to permanently remove the account: "${bank}"? This might affect your recorded balances.`,
      onConfirm: async () => {
          try {
            await onDelete?.(id);
            setConfirmModal(p => ({ ...p, show: false }));
          } catch (err) {
            setConfirmModal(p => ({ ...p, show: false }));
            setDeleteFailedModal({ show: true, accountId: id });
          }
      }
    });
  };

  const openDeactivateDialog = (id: string) => {
    setDeactivateState(s => ({
      ...s,
      show: true,
      accountId: id
    }));
  };

  const confirmDeactivateNow = async () => {
    if (!deactivateState.accountId) return;
    await onDeactivate?.(deactivateState.accountId, 'now');
    setDeactivateState({ show: false, accountId: null, month: 0, year: 0 });
  };

  const confirmDeactivateScheduled = async () => {
    if (!deactivateState.accountId) return;
    await onDeactivate?.(deactivateState.accountId, { month: deactivateState.month, year: deactivateState.year });
    setDeactivateState({ show: false, accountId: null, month: 0, year: 0 });
  };

  const renderAccount = (acc: Account) => {
    const isCredit = acc.type === 'Credit';
    const creditLimit = acc.creditLimit ?? 0;
    const usedPercent = creditLimit > 0 ? Math.min(100, Math.round((acc.balance / creditLimit) * 100)) : 0;
    const usedPercentSafe = usedPercent < 0 ? 0 : usedPercent;
    const isActive = (acc as any).isActive !== false;
    const deactivationDate = (acc as any).deactivationDate;
    const cardSurface = isCredit
      ? 'bg-[linear-gradient(140deg,#1f1b4b_0%,#3b2d7a_55%,#6d4db5_100%)] text-white'
      : 'bg-[linear-gradient(140deg,#111827_0%,#1f2937_50%,#374151_100%)] text-white';

    return (
      <div
        key={acc.id}
        className={`${cardSurface} relative overflow-hidden rounded-[2rem] border-[4px] border-black p-5 shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] transition-all duration-200 hover:-translate-y-1 hover:shadow-[12px_12px_0px_0px_rgba(0,0,0,1)]`}
      >
        <div className="absolute left-6 top-6 h-10 w-14 rounded-xl border border-white/25 bg-white/10" />
        <div className="absolute right-4 top-4 h-16 w-16 rounded-full border border-white/20 bg-white/10" />
        <div className="absolute inset-x-6 top-20 h-px bg-white/20" />

        <div className="mb-6 flex items-start justify-between">
          <div className="flex items-center gap-2">
            <span className={`rounded-full border-2 border-black px-3 py-1 text-[10px] font-black uppercase tracking-[0.24em] text-black shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] ${getAccentClasses('bg')}`}>
              {isCredit ? 'Credit' : 'Debit'}
            </span>
            <span className="rounded-full bg-white/15 px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.2em] text-white/85">
              {acc.classification}
            </span>
          </div>

          <div className="relative">
            <button
              onClick={(e) => { e.stopPropagation(); setOpenMenuId(openMenuId === acc.id ? null : acc.id); }}
              className="rounded-2xl border-2 border-black bg-white/15 p-2.5 text-white backdrop-blur transition-all hover:-rotate-6 hover:bg-white/25"
              aria-label="More options"
            >
              <MoreVertical className="w-4 h-4" />
            </button>

            {openMenuId === acc.id && (
              <div
                className="absolute right-0 z-50 mt-2 w-48 rounded-2xl border-[4px] border-black bg-white p-2 shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] transition-colors dark:bg-gray-900"
                onClick={(e) => e.stopPropagation()}
              >
                <button
                  onClick={(e) => { e.stopPropagation(); setOpenMenuId(null); openEditModal(acc); }}
                  className="w-full rounded-xl px-4 py-3 text-left text-sm font-bold text-gray-800 transition-colors hover:bg-gray-100 dark:text-gray-100 dark:hover:bg-gray-800"
                >
                  <span>Edit</span>
                </button>
                {isActive && (
                  <button
                    onClick={(e) => { e.stopPropagation(); setOpenMenuId(null); openDeactivateDialog(acc.id); }}
                    className="w-full rounded-xl px-4 py-3 text-left text-sm font-bold text-gray-800 transition-colors hover:bg-gray-100 dark:text-gray-100 dark:hover:bg-gray-800"
                  >
                    <span>Deactivate</span>
                  </button>
                )}
                <button
                  onClick={(e) => { e.stopPropagation(); setOpenMenuId(null); handleDeleteTrigger(acc.id, acc.bank); }}
                  className="w-full rounded-xl px-4 py-3 text-left text-sm font-bold text-red-600 transition-colors hover:bg-red-50 dark:text-red-400 dark:hover:bg-red-900/20"
                >
                  <span>Delete</span>
                </button>
              </div>
            )}
          </div>
        </div>

        <div className="mb-5">
          <div className="flex items-start justify-between gap-4">
            <div>
              <h3 className="max-w-[14rem] text-xl font-black leading-tight">{acc.bank}</h3>
              <p className="mt-1 text-[11px] font-bold uppercase tracking-[0.28em] text-white/70">{acc.classification}</p>
            </div>
            <div className="text-right">
              <p className="text-[10px] font-black uppercase tracking-[0.28em] text-white/60">Balance</p>
              <p className="mt-1 text-xl font-black">{formatCurrency(acc.balance)}</p>
            </div>
          </div>
        </div>

        {isCredit && (
          <div className="mb-4 rounded-[1.4rem] border-2 border-white/15 bg-black/15 p-4 backdrop-blur-sm">
            <div className="mb-2 flex items-center justify-between">
              <p className="text-xs font-bold uppercase tracking-[0.18em] text-white/70">Credit Limit</p>
              <p className="text-sm font-semibold text-white">{formatCurrency(creditLimit)}</p>
            </div>

            <div className="h-3 w-full overflow-hidden rounded-full border-2 border-black/30 bg-white/15">
              <div
                className={`h-3 rounded-full ${usedPercentSafe >= 90 ? 'bg-red-500' : 'bg-purple-300'}`}
                style={{ width: `${usedPercentSafe}%`, transition: 'width 300ms ease' }}
                aria-valuenow={usedPercentSafe}
                aria-valuemin={0}
                aria-valuemax={100}
                role="progressbar"
              />
            </div>

            <div className="mt-2 flex items-center justify-between text-[11px] text-white/75">
              <span>Used</span>
              <span className="font-medium">{usedPercentSafe}%</span>
            </div>
          </div>
        )}

        <div className="space-y-3">
          {isActive && deactivationDate && (
            <p className="text-xs font-bold text-yellow-200">
              Scheduled to deactivate: {monthNames[deactivationDate.month]} {deactivationDate.year}
            </p>
          )}
          {isCredit && acc.billingDate && (
            <p className="text-xs text-white/75">
              Statement: {new Date(acc.billingDate).getDate()}{ordinalSuffix(new Date(acc.billingDate).getDate())} each month
            </p>
          )}
          {isCredit && acc.billingDate && acc.dueDate && (
            <p className="text-xs text-white/75">
              Due: {new Date(acc.dueDate).getDate()} days after → ~{getDueDayForDisplay(new Date(acc.billingDate).getDate(), new Date(acc.dueDate).getDate())}
            </p>
          )}
        </div>

        <div className="mt-6 flex items-center justify-end gap-2">
          {isCredit && (
            <Link
              to={`/accounts/statement?account=${acc.id}`}
              onClick={(e) => e.stopPropagation()}
              className="rounded-2xl border-[3px] border-black bg-white/10 px-3 py-2 text-sm font-black text-white shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] transition-all hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none"
              aria-label={`View ${acc.bank} statement`}
            >
              View Statement
            </Link>
          )}
          <Link
            to={`/accounts/view?account=${acc.id}`}
            onClick={(e) => e.stopPropagation()}
            className={`inline-flex items-center gap-2 rounded-2xl border-[3px] border-black px-4 py-2 text-sm font-black text-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] transition-all hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none ${getAccentClasses('bg')}`}
            aria-label={`View ${acc.bank} transactions`}
          >
            <span>View</span>
            <ArrowUpRight className="h-4 w-4" />
          </Link>
        </div>
      </div>
    );
  };

  const debitAccounts = accounts.filter(a => a.type === 'Debit');
  const creditAccounts = accounts.filter(a => a.type === 'Credit');

  return (
    <div className="space-y-12 animate-in fade-in duration-500" onClick={() => setOpenMenuId(null)}>
      {/* Loading State */}
      {loading && (
        <div className="flex items-center justify-center py-12">
          <div className="text-center">
            <div className="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-600 mb-4"></div>
            <p className="text-gray-600 font-medium">Loading accounts from database...</p>
          </div>
        </div>
      )}

      {/* Error State */}
      {error && !loading && (
        <div className="bg-red-50 border border-red-200 rounded-xl p-4 mb-6">
          <div className="flex items-start space-x-3">
            <AlertTriangle className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
            <div>
              <h3 className="text-sm font-semibold text-red-800">Error Loading Accounts</h3>
              <p className="text-sm text-red-600 mt-1">{error}</p>
            </div>
          </div>
        </div>
      )}

      {/* Main Content */}
      {!loading && (
      <>
      <PageHeader 
        title="Accounts"
        subtitle="Cards and vaults at a glance"
        icon={
          <div className={`w-14 h-14 rounded-2xl flex items-center justify-center text-white border-[3px] border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] -rotate-3 transition-all hover:rotate-0 hover:scale-110 z-10 relative ${getAccentClasses('bg')}`}>
            <WalletCards className="w-7 h-7" />
          </div>
        }
        actions={
          <div className="flex items-center gap-3 flex-wrap justify-end">
            <Link to="/transactions" className="flex items-center gap-2 rounded-2xl border-[3px] border-black bg-white px-5 py-3 text-sm font-black text-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] transition-all hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none dark:bg-gray-900 dark:text-white">
              <Sparkles className="w-4 h-4" />
              <span className="hidden sm:inline">Transactions</span>
              <span className="sm:hidden">Ledger</span>
            </Link>
            <button onClick={openAddModal} className={`flex items-center gap-2 text-white px-5 py-3 rounded-2xl border-[3px] border-black font-black transition-all text-sm shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none ${getAccentClasses('bg')}`}>
              <Plus className="w-4 h-4" />
              <span className="hidden sm:inline">Add Account</span>
              <span className="sm:hidden">Add</span>
            </button>
          </div>
        }
      />

      {/* Empty State */}
      {debitAccounts.length === 0 && creditAccounts.length === 0 && (
        <div className="rounded-[2rem] border-[4px] border-dashed border-black bg-yellow-100 px-8 py-12 text-center shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]">
          <div className={`mx-auto mb-4 inline-flex h-20 w-20 items-center justify-center rounded-[2rem] border-[4px] border-black ${getAccentClasses('bg')} text-white shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]`}>
            <WalletCards className="w-10 h-10" />
          </div>
          <h3 className="mb-2 text-xl font-black text-gray-900 dark:text-gray-100">No Accounts Yet</h3>
          <p className="mb-6 text-gray-700 dark:text-gray-300">Get started by adding your first account</p>
          <button 
            onClick={openAddModal}
            className={`inline-flex items-center gap-2 border-[3px] border-black px-6 py-3 rounded-2xl font-black text-white shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] transition-all hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none ${getAccentClasses('bg')}`}
          >
            <Plus className="w-5 h-5" />
            <span>Add Your First Account</span>
          </button>
        </div>
      )}

      <section>
        <button 
          onClick={() => setIsDebitOpen(!isDebitOpen)}
          className="mb-6 flex w-full items-center gap-3 rounded-[1.6rem] border-[4px] border-black bg-white px-5 py-4 text-left shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] transition-all hover:-translate-y-0.5 dark:bg-gray-900"
        >
          {isDebitOpen ? <ChevronDown className="w-5 h-5" /> : <ChevronRight className="w-5 h-5" />}
          <TrendingUp className="w-5 h-5 text-green-500" />
          <div>
            <h3 className="text-sm font-black uppercase tracking-[0.24em] text-gray-800 dark:text-gray-100">Debit & Assets</h3>
            <p className="text-xs font-bold text-gray-500 dark:text-gray-400">{debitAccounts.length} account{debitAccounts.length !== 1 ? 's' : ''}</p>
          </div>
        </button>
        {isDebitOpen && (
          <div className="grid grid-cols-1 gap-6 md:grid-cols-2 xl:grid-cols-3">
            {debitAccounts.map(renderAccount)}
          </div>
        )}
      </section>

      <section>
        <button 
          onClick={() => setIsCreditOpen(!isCreditOpen)}
          className="mb-6 flex w-full items-center gap-3 rounded-[1.6rem] border-[4px] border-black bg-white px-5 py-4 text-left shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] transition-all hover:-translate-y-0.5 dark:bg-gray-900"
        >
          {isCreditOpen ? <ChevronDown className="w-5 h-5" /> : <ChevronRight className="w-5 h-5" />}
          <CreditCard className="w-5 h-5 text-purple-500" />
          <div>
            <h3 className="text-sm font-black uppercase tracking-[0.24em] text-gray-800 dark:text-gray-100">Credit & Liabilities</h3>
            <p className="text-xs font-bold text-gray-500 dark:text-gray-400">{creditAccounts.length} account{creditAccounts.length !== 1 ? 's' : ''}</p>
          </div>
        </button>
        {isCreditOpen && (
          <div className="grid grid-cols-1 gap-6 md:grid-cols-2 xl:grid-cols-3">
            {creditAccounts.map(renderAccount)}
          </div>
        )}
      </section>
      </>
      )}

      {showModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-md">
          <div className="w-full max-w-3xl overflow-hidden rounded-[2rem] border-[4px] border-black bg-[#fff7e8] shadow-[10px_10px_0px_0px_rgba(0,0,0,1)] flex flex-col md:flex-row transition-colors dark:bg-gray-900">
            <div className={`${getAccentClasses('bg')} md:w-1/3 p-8 text-white flex flex-col justify-between transition-colors border-b-[4px] border-black md:border-b-0 md:border-r-[4px]`}>
              <div>
                <div className="mb-5 inline-flex rounded-2xl border-[3px] border-black bg-white/20 p-3">
                  <WalletCards className="w-8 h-8" />
                </div>
                <h2 className="text-2xl font-black mb-2 uppercase text-white">{editingId ? 'Edit Account' : 'Add Account'}</h2>
                <p className="text-sm text-white/85">Keep your banking setup bold, playful, and easy to scan.</p>
              </div>
            </div>
            <form onSubmit={handleSubmit} className="p-8 flex-1 bg-[#fff7e8] dark:bg-gray-900 space-y-6 transition-colors">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-black text-gray-500 uppercase tracking-[0.2em] mb-2 transition-colors">Bank Name</label>
                  <input required type="text" value={formData.bank} onChange={(e) => setFormData({...formData, bank: e.target.value})} className="w-full rounded-2xl border-[3px] border-black bg-white px-4 py-3 font-bold text-gray-900 outline-none transition-colors dark:bg-gray-800 dark:text-gray-100" />
                </div>
                <div>
                  <label className="block text-xs font-black text-gray-500 uppercase tracking-[0.2em] mb-2 transition-colors">Type</label>
                  <select value={formData.type} onChange={(e) => setFormData({...formData, type: e.target.value as 'Debit' | 'Credit'})} className="w-full rounded-2xl border-[3px] border-black bg-white px-4 py-3 font-bold text-gray-900 outline-none transition-colors dark:bg-gray-800 dark:text-gray-100">
                    <option value="Debit">Debit</option>
                    <option value="Credit">Credit</option>
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-black text-gray-500 uppercase tracking-[0.2em] mb-2 transition-colors">Classification</label>
                  <select value={formData.classification} onChange={(e) => setFormData({...formData, classification: e.target.value as AccountClassification})} className="w-full rounded-2xl border-[3px] border-black bg-white px-4 py-3 font-bold text-gray-900 outline-none transition-colors dark:bg-gray-800 dark:text-gray-100">
                    <option>Checking</option>
                    <option>Savings</option>
                    <option>Investment</option>
                    <option>Loan</option>
                    <option>Other</option>
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-black text-gray-500 uppercase tracking-[0.2em] mb-2 transition-colors">Opening Balance</label>
                  <input required type="number" value={formData.balance} onChange={(e) => setFormData({...formData, balance: e.target.value})} className="w-full rounded-2xl border-[3px] border-black bg-white px-4 py-3 font-bold text-gray-900 outline-none transition-colors dark:bg-gray-800 dark:text-gray-100" />
                </div>
              </div>

              {formData.type === 'Credit' && (
                <div className="rounded-[1.6rem] border-[3px] border-black bg-white p-4 shadow-[5px_5px_0px_0px_rgba(0,0,0,1)] dark:bg-gray-950">
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                    <div>
                      <label className="block text-xs font-black text-gray-500 uppercase tracking-[0.2em] mb-2 transition-colors">Credit Limit</label>
                      <input type="number" value={formData.creditLimit} onChange={(e) => setFormData({...formData, creditLimit: e.target.value})} className="w-full rounded-2xl border-[3px] border-black bg-[#fff7e8] px-4 py-3 font-bold text-gray-900 outline-none transition-colors dark:bg-gray-800 dark:text-gray-100" />
                    </div>
                    <div>
                      <label className="block text-xs font-black text-gray-500 uppercase tracking-[0.2em] mb-2 transition-colors">Statement Day</label>
                      <input type="number" min="1" max="31" placeholder="e.g. 12" value={formData.billingDate} onChange={(e) => setFormData({...formData, billingDate: e.target.value})} className="w-full rounded-2xl border-[3px] border-black bg-[#fff7e8] px-4 py-3 font-bold text-gray-900 outline-none transition-colors dark:bg-gray-800 dark:text-gray-100" />
                    </div>
                    <div>
                      <label className="block text-xs font-black text-gray-500 uppercase tracking-[0.2em] mb-2 transition-colors">Days to Pay</label>
                      <input type="number" min="1" max="60" placeholder="e.g. 21" value={formData.dueDate} onChange={(e) => setFormData({...formData, dueDate: e.target.value})} className="w-full rounded-2xl border-[3px] border-black bg-[#fff7e8] px-4 py-3 font-bold text-gray-900 outline-none transition-colors dark:bg-gray-800 dark:text-gray-100" />
                    </div>
                  </div>
                  {formData.billingDate && formData.dueDate && (() => {
                    const statementDay = parseInt(formData.billingDate);
                    const daysToPay = parseInt(formData.dueDate);
                    if (isNaN(statementDay) || isNaN(daysToPay)) return null;
                    const displayStr = getDueDayForDisplay(statementDay, daysToPay);
                    return (
                      <p className="mt-3 text-xs font-bold text-purple-700 dark:text-purple-300 transition-colors">
                        Statement cuts on the {statementDay}{ordinalSuffix(statementDay)} · Due around {displayStr}
                      </p>
                    );
                  })()}
                </div>
              )}

              <div className="flex flex-col-reverse sm:flex-row gap-4 pt-4">
                <button type="button" onClick={() => { setShowModal(false); resetForm(); }} className="flex-1 rounded-2xl border-[3px] border-black bg-white py-4 font-black text-gray-700 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] transition-all hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none dark:bg-gray-800 dark:text-gray-100">Cancel</button>
                <button type="submit" className={`flex-1 rounded-2xl border-[3px] border-black py-4 font-black text-white shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] transition-all hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none ${getAccentClasses('bg')}`}>{editingId ? 'Save Changes' : 'Add Account'}</button>
              </div>
            </form>
          </div>
        </div>
      )}

      {deactivateState.show && (
        <DeactivateDialog
          accountId={deactivateState.accountId!}
          accounts={accounts}
          month={deactivateState.month}
          year={deactivateState.year}
          onChangeMonth={(m) => setDeactivateState(s => ({ ...s, month: m }))}
          onChangeYear={(y) => setDeactivateState(s => ({ ...s, year: y }))}
          onClose={() => setDeactivateState({ show: false, accountId: null, month: 0, year: 0 })}
          onNow={() => confirmDeactivateNow()}
          onSchedule={() => confirmDeactivateScheduled()}
        />
      )}

      {deleteFailedModal.show && (
        <div className="fixed inset-0 z-[200] flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm animate-in fade-in">
          <div className="bg-[#fff7e8] dark:bg-gray-900 rounded-[2rem] border-[4px] border-black w-full max-w-sm p-8 shadow-[10px_10px_0px_0px_rgba(0,0,0,1)] animate-in zoom-in-95 flex flex-col items-center text-center transition-colors">
            <div className="w-16 h-16 bg-orange-200 text-orange-700 rounded-3xl border-[3px] border-black flex items-center justify-center mb-6 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] transition-colors">
              <AlertTriangle className="w-8 h-8" />
            </div>
            <h3 className="text-xl font-black text-gray-900 dark:text-gray-100 mb-2 uppercase tracking-tight transition-colors">Cannot Delete</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400 mb-8 font-medium leading-relaxed transition-colors">This account cannot be deleted because it has attached transactions, wallets, or schedules. Would you like to deactivate it instead?</p>
            <div className="flex flex-col w-full space-y-3">
              <button onClick={() => { 
                setDeleteFailedModal({ show: false, accountId: '' }); 
                openDeactivateDialog(deleteFailedModal.accountId); 
              }} className={`w-full py-4 rounded-2xl border-[3px] border-black font-black uppercase tracking-widest text-[10px] text-white transition-all shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none ${getAccentClasses('bg')}`}>
                Deactivate Instead
              </button>
              <button onClick={() => setDeleteFailedModal({ show: false, accountId: '' })} className="w-full bg-white dark:bg-gray-800 text-gray-600 dark:text-gray-300 py-4 rounded-2xl border-[3px] border-black font-black uppercase tracking-widest text-[10px] transition-all shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none">
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}

      {confirmModal.show && <ConfirmDialog {...confirmModal} onClose={() => setConfirmModal(p => ({ ...p, show: false }))} />}
    </div>
  );
};

const DeactivateDialog: React.FC<{
  accountId: string;
  accounts: Account[];
  month: number;
  year: number;
  onChangeMonth: (m: number) => void;
  onChangeYear: (y: number) => void;
  onClose: () => void;
  onNow: () => Promise<void>;
  onSchedule: () => Promise<void>;
}> = ({ accountId, accounts, month, year, onChangeMonth, onChangeYear, onClose, onNow, onSchedule }) => {
  const now = new Date();
  const currentYear = now.getFullYear();
  const years = Array.from({ length: 6 }, (_, i) => currentYear + i);

  const [linkedWallets, setLinkedWallets] = useState<any[]>([]);
  const [reassignAccountId, setReassignAccountId] = useState('');
  const [isLoadingWallets, setIsLoadingWallets] = useState(true);
  const [isProcessing, setIsProcessing] = useState(false);

  useEffect(() => {
    const fetchWallets = async () => {
      setIsLoadingWallets(true);
      try {
        const isTestMode = localStorage.getItem('test_environment_enabled') === 'true';
        const tableName = isTestMode ? 'wallets_test' : 'wallets';
        const { data, error } = await supabase.from(tableName).select('*').eq('account_id', accountId);
        if (!error && data) setLinkedWallets(data);
      } catch (e) {
        console.error(e);
      } finally {
        setIsLoadingWallets(false);
      }
    };
    if (accountId) fetchWallets();
  }, [accountId]);

  const handleAction = async (action: 'now' | 'schedule') => {
    if (linkedWallets.length > 0 && !reassignAccountId) {
      alert('Please select a new account for the linked wallets before proceeding.');
      return;
    }
    setIsProcessing(true);
    try {
      if (linkedWallets.length > 0 && reassignAccountId) {
        const isTestMode = localStorage.getItem('test_environment_enabled') === 'true';
        const tableName = isTestMode ? 'wallets_test' : 'wallets';
        for (const w of linkedWallets) {
          await supabase.from(tableName).update({ account_id: reassignAccountId }).eq('id', w.id);
        }
      }
      if (action === 'now') await onNow();
      else await onSchedule();
    } catch (e) {
      console.error(e);
      alert('Failed to process deactivation.');
    } finally {
      setIsProcessing(false);
    }
  };

  const eligibleAccounts = accounts.filter(a => a.id !== accountId && a.type !== 'Credit');

  return (
    <div className="fixed inset-0 z-[200] flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm animate-in fade-in">
      <div className="w-full max-w-md rounded-[2rem] border-[4px] border-black bg-[#fff7e8] p-6 sm:p-8 shadow-[10px_10px_0px_0px_rgba(0,0,0,1)] animate-in zoom-in-95 transition-colors dark:bg-gray-900">
        <h3 className="text-xl font-black text-gray-900 dark:text-gray-100 mb-2 uppercase tracking-tight transition-colors">Deactivate Account</h3>
        <p className="text-sm text-gray-500 dark:text-gray-400 mb-6 font-medium leading-relaxed transition-colors">Choose whether to deactivate the account now or schedule deactivation for a later month and year.</p>

        {!isLoadingWallets && linkedWallets.length > 0 && (
          <div className="mb-6 rounded-[1.5rem] border-[3px] border-black bg-orange-100 p-4 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] transition-colors">
            <div className="flex items-center space-x-2 mb-2">
              <AlertTriangle className="w-4 h-4 text-orange-600" />
              <p className="text-xs font-bold text-orange-800">Wallets Linked</p>
            </div>
            <p className="text-xs text-orange-700 mb-3">
              This account has {linkedWallets.length} linked wallet(s). Please select a new debit account to reassign them to.
            </p>
            <select 
              value={reassignAccountId} 
              onChange={(e) => setReassignAccountId(e.target.value)} 
              className="w-full rounded-2xl border-[3px] border-black bg-white px-4 py-3 text-sm font-bold text-gray-700 outline-none transition-colors"
            >
              <option value="">-- Select New Account --</option>
              {eligibleAccounts.map(a => (
                <option key={a.id} value={a.id}>{a.bank} ({a.classification})</option>
              ))}
            </select>
            {eligibleAccounts.length === 0 && (
              <p className="text-[10px] text-red-500 mt-1 font-bold">No other debit accounts available to receive wallets.</p>
            )}
          </div>
        )}

        <div className="space-y-4">
          <PinProtectedAction
            featureId="account_deactivations"
            onVerified={() => handleAction('now')}
            actionLabel="Deactivate Account"
          >
            <button onClick={(e) => e.preventDefault()} disabled={isProcessing} className="w-full rounded-2xl border-[3px] border-black bg-red-600 text-white py-3.5 font-black uppercase tracking-widest shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] transition-all hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none disabled:opacity-50">
              {isProcessing ? 'Processing...' : 'Deactivate Now'}
            </button>
          </PinProtectedAction>

          <div className="rounded-[1.5rem] border-[3px] border-black bg-white p-4 transition-colors dark:bg-gray-950">
            <p className="text-sm text-gray-600 dark:text-gray-300 mb-2 font-black uppercase tracking-[0.16em] transition-colors">Deactivate on</p>
            <div className="flex flex-col sm:flex-row gap-2">
              <select value={month} onChange={(e) => onChangeMonth(parseInt(e.target.value, 10))} className="flex-1 rounded-2xl border-[3px] border-black bg-[#fff7e8] text-gray-900 dark:text-gray-100 px-3 py-3 outline-none transition-colors dark:bg-gray-800">
                {monthNames.map((mName, idx) => <option key={idx} value={idx}>{mName}</option>)}
              </select>
              <select value={year} onChange={(e) => onChangeYear(parseInt(e.target.value, 10))} className="w-full sm:w-28 rounded-2xl border-[3px] border-black bg-[#fff7e8] text-gray-900 dark:text-gray-100 px-3 py-3 outline-none transition-colors dark:bg-gray-800">
                {years.map(y => <option key={y} value={y}>{y}</option>)}
              </select>
            </div>
            <div className="mt-4">
            <PinProtectedAction
              featureId="account_deactivations"
              onVerified={() => handleAction('schedule')}
              actionLabel="Schedule Deactivation"
            >
              <button onClick={(e) => e.preventDefault()} disabled={isProcessing} className="w-full rounded-2xl border-[3px] border-black bg-indigo-600 text-white py-3 font-black uppercase tracking-[0.18em] shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] transition-all hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none disabled:opacity-50">{isProcessing ? 'Processing...' : 'Schedule Deactivation'}</button>
            </PinProtectedAction>
            </div>
          </div>

          <button onClick={onClose} disabled={isProcessing} className="w-full rounded-2xl border-[3px] border-black bg-white dark:bg-gray-800 text-gray-600 dark:text-gray-300 py-3.5 font-black uppercase tracking-widest shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] transition-all hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none disabled:opacity-50">
            Cancel
          </button>
        </div>
      </div>
    </div>
  );
};

const ConfirmDialog: React.FC<{ show: boolean; title: string; message: string; onConfirm: () => void; onClose: () => void }> = ({ title, message, onConfirm, onClose }) => (
  <div className="fixed inset-0 z-[200] flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm animate-in fade-in">
    <div className="bg-[#fff7e8] dark:bg-gray-900 rounded-[2rem] border-[4px] border-black w-full max-w-sm p-8 shadow-[10px_10px_0px_0px_rgba(0,0,0,1)] animate-in zoom-in-95 flex flex-col items-center text-center transition-colors">
      <div className="w-16 h-16 bg-red-200 text-red-700 rounded-3xl border-[3px] border-black flex items-center justify-center mb-6 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] transition-colors">
        <AlertTriangle className="w-8 h-8" />
      </div>
      <h3 className="text-xl font-black text-gray-900 dark:text-gray-100 mb-2 uppercase tracking-tight transition-colors">{title}</h3>
      <p className="text-sm text-gray-500 dark:text-gray-400 mb-8 font-medium leading-relaxed transition-colors">{message}</p>
      <div className="flex flex-col w-full space-y-3">
        <PinProtectedAction
          featureId="account_deletions"
          onVerified={onConfirm}
          actionLabel="Delete Account"
        >
          <button onClick={(e) => e.preventDefault()} className="w-full rounded-2xl border-[3px] border-black bg-red-600 text-white py-4 font-black uppercase tracking-widest text-[10px] transition-all shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none">
            Proceed
          </button>
        </PinProtectedAction>
        <button onClick={onClose} className="w-full rounded-2xl border-[3px] border-black bg-white dark:bg-gray-800 text-gray-500 dark:text-gray-300 py-4 font-black uppercase tracking-widest text-[10px] transition-all shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none">
          Cancel
        </button>
      </div>
    </div>
  </div>
);

export default Accounts;
