import React, { useState } from 'react';
import { Installment, Account, ViewMode, Biller, Transaction } from '../types';
import { Plus, LayoutGrid, List, Wallet, Trash2, X, Upload, AlertTriangle, Edit2, Eye, MoreVertical } from 'lucide-react';
import { getPaymentSchedulesByMonthYear } from '../src/services/paymentSchedulesService';
import { markPaymentScheduleAsPaid } from '../src/services/paymentSchedulesService';
import { createTransaction } from '../src/services/transactionsService';
import { MONTHS_ORDERED } from '../src/services/paymentSchedulesService';

interface InstallmentsProps {
  installments: Installment[];
  accounts: Account[];
  billers?: Biller[];
  onAdd: (i: Installment) => Promise<void>;
  onUpdate?: (i: Installment) => Promise<void>;
  onDelete?: (id: string) => Promise<void>;
  loading?: boolean;
  error?: string | null;
  transactions?: Transaction[]; // For checking paid status
}

const Installments: React.FC<InstallmentsProps> = ({ 
  installments, 
  accounts, 
  billers = [], 
  onAdd, 
  onUpdate, 
  onDelete, 
  loading = false, 
  error = null,
  transactions = [] 
}) => {
  const [viewMode, setViewMode] = useState<ViewMode>('card');
  const [showModal, setShowModal] = useState(false);
  const [showPayModal, setShowPayModal] = useState<Installment | null>(null);
  const [showEditModal, setShowEditModal] = useState<Installment | null>(null);
  const [showViewModal, setShowViewModal] = useState<Installment | null>(null);
  const [openMenuId, setOpenMenuId] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const [confirmModal, setConfirmModal] = useState<{
    show: boolean;
    title: string;
    message: string;
    onConfirm: () => void;
  }>({
    show: false,
    title: '',
    message: '',
    onConfirm: () => {},
  });
  
  const [formData, setFormData] = useState({ 
    name: '', totalAmount: '', monthlyAmount: '', termDuration: '', paidAmount: '', accountId: accounts[0]?.id || '', startDate: '', billerId: '', timing: '1/2' as '1/2' | '2/2'
  });

  const [editFormData, setEditFormData] = useState({ 
    name: '', totalAmount: '', monthlyAmount: '', termDuration: '', paidAmount: '', accountId: '', startDate: '', billerId: '', timing: '1/2' as '1/2' | '2/2'
  });

  const [payFormData, setPayFormData] = useState({
    amount: '',
    receipt: '',
    datePaid: new Date().toISOString().split('T')[0],
    accountId: accounts[0]?.id || ''
  });

  const formatCurrency = (val: number) => {
    return new Intl.NumberFormat('en-PH', { 
      style: 'currency', 
      currency: 'PHP',
      minimumFractionDigits: 2,
      maximumFractionDigits: 2 
    }).format(val);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isSubmitting) return;

    setIsSubmitting(true);
    try {
      // QA: Format termDuration with " months" suffix for consistency
      const termDurationFormatted = formData.termDuration ? `${formData.termDuration} months` : '12 months';
      
      await onAdd({
        id: '', // ID will be generated by Supabase
        name: formData.name,
        totalAmount: parseFloat(formData.totalAmount),
        monthlyAmount: parseFloat(formData.monthlyAmount),
        termDuration: termDurationFormatted,
        paidAmount: parseFloat(formData.paidAmount) || 0,
        accountId: formData.accountId,
        startDate: formData.startDate || undefined,
        billerId: formData.billerId || undefined,
        timing: formData.timing // PROTOTYPE: Include timing field
      });
      setShowModal(false);
      setFormData({ name: '', totalAmount: '', monthlyAmount: '', termDuration: '', paidAmount: '', accountId: accounts[0]?.id || '', startDate: '', billerId: '', timing: '1/2' });
    } catch (error) {
      console.error('Failed to add installment:', error);
      // PROTOTYPE: Show helpful message if timing column is missing
      const errorMessage = error instanceof Error ? error.message : String(error);
      if (errorMessage.includes('Database migration required')) {
        alert('⚠️ Database Setup Required\n\nThe timing feature requires a database update. Please run the migration in Supabase.\n\nSee HOW_TO_ADD_TIMING_COLUMN.md for step-by-step instructions.');
      } else {
        alert('Failed to add installment. Please try again.');
      }
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleEditSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!showEditModal || isSubmitting) return;
    
    setIsSubmitting(true);
    try {
      // QA: Format termDuration with " months" suffix for consistency
      const termDurationFormatted = editFormData.termDuration ? `${editFormData.termDuration} months` : '12 months';
      
      const updatedInstallment: Installment = {
        ...showEditModal,
        name: editFormData.name,
        totalAmount: parseFloat(editFormData.totalAmount),
        monthlyAmount: parseFloat(editFormData.monthlyAmount),
        termDuration: termDurationFormatted,
        paidAmount: parseFloat(editFormData.paidAmount) || 0,
        accountId: editFormData.accountId,
        startDate: editFormData.startDate || undefined,
        billerId: editFormData.billerId || undefined,
        timing: editFormData.timing // PROTOTYPE: Include timing field
      };

      await onUpdate?.(updatedInstallment);
      setShowEditModal(null);
    } catch (error) {
      console.error('Failed to update installment:', error);
      // PROTOTYPE: Show helpful message if timing column is missing
      const errorMessage = error instanceof Error ? error.message : String(error);
      if (errorMessage.includes('Database migration required')) {
        alert('⚠️ Database Setup Required\n\nThe timing feature requires a database update. Please run the migration in Supabase.\n\nSee HOW_TO_ADD_TIMING_COLUMN.md for step-by-step instructions.');
      } else {
        alert('Failed to update installment. Please try again.');
      }
    } finally {
      setIsSubmitting(false);
    }
  };

  const handlePaySubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!showPayModal || isSubmitting) return;

    setIsSubmitting(true);
    try {
      const paymentAmount = parseFloat(payFormData.amount) || 0;
      
      console.log('[Installments] Processing payment:', {
        installmentId: showPayModal.id,
        installmentName: showPayModal.name,
        paymentAmount: paymentAmount,
        accountId: payFormData.accountId,
        datePaid: payFormData.datePaid
      });

      // CRITICAL: Find the payment schedule for the current month
      const currentDate = new Date(payFormData.datePaid);
      const currentMonth = MONTHS_ORDERED[currentDate.getMonth()];
      const currentYear = currentDate.getFullYear().toString();
      
      console.log('[Installments] Finding payment schedule for:', {
        month: currentMonth,
        year: currentYear,
        installmentId: showPayModal.id
      });
      
      // Get all schedules for this month/year
      const { data: schedules, error: scheduleError } = await getPaymentSchedulesByMonthYear(
        currentMonth,
        currentYear
      );
      
      if (scheduleError) {
        console.error('[Installments] Error fetching payment schedules:', scheduleError);
        throw new Error('Failed to find payment schedule. Please try again.');
      }
      
      // Find the schedule for this installment
      const paymentSchedule = schedules?.find(s => s.installment_id === showPayModal.id);
      
      if (!paymentSchedule) {
        console.error('[Installments] Payment schedule not found for:', {
          installmentId: showPayModal.id,
          month: currentMonth,
          year: currentYear
        });
        alert(`Payment schedule not found for ${currentMonth} ${currentYear}. The installment may not have schedules for this month. Please refresh the page or contact support.`);
        setIsSubmitting(false);
        return;
      }
      
      console.log('[Installments] Found payment schedule:', paymentSchedule.id);
      
      // CRITICAL: Create transaction WITH payment_schedule_id linkage
      const transactionData = {
        name: `${showPayModal.name} - ${currentMonth} ${currentYear}`,
        amount: paymentAmount,
        date: payFormData.datePaid,
        payment_method_id: payFormData.accountId,
        type: 'expense' as const,
        category: 'Installment Payment',
        receipt: payFormData.receipt || null,
        payment_schedule_id: paymentSchedule.id // CRITICAL: Link to payment schedule
      };
      
      console.log('[Installments] Creating transaction with payment_schedule_id:', paymentSchedule.id);
      
      const { data: transaction, error: transactionError } = await createTransaction(transactionData);
      
      if (transactionError || !transaction) {
        console.error('[Installments] Error creating transaction:', transactionError);
        throw new Error('Failed to create transaction. Please try again.');
      }
      
      console.log('[Installments] Transaction created successfully:', transaction.id);
      
      // Mark the payment schedule as paid
      const { error: markPaidError } = await markPaymentScheduleAsPaid(
        paymentSchedule.id,
        paymentAmount,
        payFormData.datePaid,
        payFormData.accountId,
        payFormData.receipt || undefined
      );
      
      if (markPaidError) {
        console.error('[Installments] Error marking schedule as paid:', markPaidError);
        // Don't fail - transaction was created, just log the error
        console.warn('[Installments] Schedule not marked as paid but transaction exists');
      } else {
        console.log('[Installments] Payment schedule marked as paid');
      }
      
      // Update installment's total paidAmount
      const updatedInstallment: Installment = {
        ...showPayModal,
        paidAmount: showPayModal.paidAmount + paymentAmount
      };

      await onUpdate?.(updatedInstallment);
      
      console.log('[Installments] Payment processed successfully');
      
      // Close pay modal after successful payment
      setShowPayModal(null);
      setPayFormData({
        amount: '',
        receipt: '',
        datePaid: new Date().toISOString().split('T')[0],
        accountId: accounts[0]?.id || ''
      });
      
      // If view modal is open, refresh it with updated installment data
      if (showViewModal && showViewModal.id === updatedInstallment.id) {
        setShowViewModal(updatedInstallment);
      }
    } catch (error) {
      console.error('[Installments] Failed to process payment:', error);
      const errorMessage = error instanceof Error ? error.message : 'Failed to process payment. Please try again.';
      alert(errorMessage);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleDeleteTrigger = (id: string, name: string) => {
    setConfirmModal({
      show: true,
      title: 'Remove Installment',
      message: `Are you sure you want to permanently stop tracking the installment for "${name}"?`,
      onConfirm: async () => {
        await onDelete?.(id);
        setConfirmModal(p => ({ ...p, show: false }));
      }
    });
  };

  const openEditModal = (item: Installment) => {
    // QA: Extract numeric value from termDuration (e.g., "12 months" -> "12")
    const termDurationNumeric = item.termDuration ? item.termDuration.replace(/\D/g, '') : '';
    
    setEditFormData({
      name: item.name,
      totalAmount: item.totalAmount.toString(),
      monthlyAmount: item.monthlyAmount.toString(),
      termDuration: termDurationNumeric,
      paidAmount: item.paidAmount.toString(),
      accountId: item.accountId,
      startDate: item.startDate || '',
      billerId: item.billerId || '',
      timing: item.timing || '1/2' // PROTOTYPE: Default to 1/2 if not set
    });
    setShowEditModal(item);
    setOpenMenuId(null);
  };

  const renderCard = (item: Installment) => {
    const progress = (item.paidAmount / item.totalAmount) * 100;
    const remaining = item.totalAmount - item.paidAmount;
    const account = accounts.find(a => a.id === item.accountId);

    return (
      <div key={item.id} className="bg-white p-6 rounded-3xl shadow-sm border border-gray-100 hover:shadow-md transition-all group relative overflow-hidden">
        <div className="flex justify-between items-start mb-4">
          <div className="flex-1">
            <div className="flex items-center gap-2 mb-1">
              <h3 className="font-black text-lg text-gray-900 group-hover:text-indigo-600 transition-colors uppercase tracking-tight">{item.name}</h3>
              {/* PROTOTYPE: Timing badge */}
              {item.timing && (
                <span className="text-[10px] font-bold px-2 py-0.5 bg-blue-50 rounded text-blue-500">{item.timing}</span>
              )}
            </div>
            <span className="text-[10px] font-black text-gray-400 uppercase tracking-widest">{item.termDuration}</span>
          </div>
          <div className="relative">
            <button 
              onClick={() => setOpenMenuId(openMenuId === item.id ? null : item.id)}
              className="p-2 text-gray-400 hover:text-gray-600 rounded-xl transition-all"
            >
              <MoreVertical className="w-5 h-5" />
            </button>
            {openMenuId === item.id && (
              <>
                <div className="fixed inset-0 z-[10]" onClick={() => setOpenMenuId(null)}></div>
                <div className="absolute right-0 top-full mt-2 w-44 bg-white rounded-xl shadow-xl border border-gray-100 py-2 z-[20]">
                  <button 
                    onClick={() => { setShowViewModal(item); setOpenMenuId(null); }}
                    className="w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-50 flex items-center space-x-2"
                  >
                    <Eye className="w-4 h-4" />
                    <span>View Schedule</span>
                  </button>
                  <button 
                    onClick={() => openEditModal(item)}
                    className="w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-50 flex items-center space-x-2"
                  >
                    <Edit2 className="w-4 h-4" />
                    <span>Edit</span>
                  </button>
                  <div className="border-t border-gray-100 my-1"></div>
                  <button 
                    onClick={() => handleDeleteTrigger(item.id, item.name)}
                    className="w-full text-left px-4 py-2 text-sm text-red-500 hover:bg-red-50 flex items-center space-x-2"
                  >
                    <Trash2 className="w-4 h-4" />
                    <span>Delete</span>
                  </button>
                </div>
              </>
            )}
          </div>
        </div>
        
        <div className="grid grid-cols-2 gap-4 mb-6">
          <div>
            <p className="text-[10px] text-gray-400 uppercase font-black tracking-widest">Monthly</p>
            <p className="font-black text-gray-900">{formatCurrency(item.monthlyAmount)}</p>
          </div>
          <div className="text-right">
            <p className="text-[10px] text-gray-400 uppercase font-black tracking-widest">Start Date</p>
            <p className="font-black text-gray-900">{item.startDate || 'N/A'}</p>
          </div>
        </div>

        <div className="space-y-2 mb-6">
          <div className="flex justify-between text-[10px] font-black uppercase tracking-widest">
            <span className="text-indigo-600">Paid: {formatCurrency(item.paidAmount)}</span>
            <span className="text-gray-400">Bal: {formatCurrency(remaining)}</span>
          </div>
          <div className="h-2.5 w-full bg-gray-100 rounded-full overflow-hidden">
            <div 
              className="h-full bg-indigo-500 transition-all duration-1000" 
              style={{ width: `${Math.min(progress, 100)}%` }}
            ></div>
          </div>
        </div>

        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-2 text-[10px] font-black text-gray-400 uppercase tracking-widest">
            <Wallet className="w-3.5 h-3.5" />
            <span>{account?.bank || 'Account'}</span>
          </div>
          <div className="flex items-center space-x-2">
            <button 
              onClick={() => { setShowViewModal(item); }}
              className="bg-gray-100 text-gray-700 px-4 py-2 rounded-xl text-xs font-black uppercase tracking-widest hover:bg-gray-200 transition-all"
            >
              View
            </button>
            <button 
              onClick={() => {
                setShowPayModal(item);
                setPayFormData({ ...payFormData, amount: item.monthlyAmount.toString() });
              }}
              className="bg-indigo-600 text-white px-5 py-2 rounded-xl text-xs font-black uppercase tracking-widest hover:bg-indigo-700 transition-all shadow-lg shadow-indigo-100"
            >
              Pay
            </button>
          </div>
        </div>
      </div>
    );
  };

  const renderListItem = (item: Installment) => {
    const progress = (item.paidAmount / item.totalAmount) * 100;
    const account = accounts.find(a => a.id === item.accountId);

    return (
      <div key={item.id} className="bg-white p-4 pr-6 rounded-2xl border border-gray-100 flex flex-col md:flex-row md:items-center justify-between gap-4 hover:bg-gray-50 transition-colors group">
        <div className="flex-1">
          <div className="flex items-center space-x-2">
            <h3 className="font-black text-gray-900 uppercase tracking-tight">{item.name}</h3>
            <span className="text-[10px] bg-gray-100 px-2 py-0.5 rounded-full text-gray-500 font-black uppercase tracking-widest">{item.termDuration}</span>
          </div>
          <div className="flex items-center space-x-4 mt-1">
            <p className="text-[10px] text-gray-400 font-black uppercase tracking-widest">{account?.bank || 'Account'}</p>
            <p className="text-[10px] text-gray-500 font-black">Start: {item.startDate || 'N/A'}</p>
          </div>
        </div>
        
        <div className="flex flex-1 items-center space-x-6">
           <div className="flex-1 h-2 bg-gray-100 rounded-full overflow-hidden">
             <div className="h-full bg-indigo-500" style={{ width: `${Math.min(progress, 100)}%` }}></div>
           </div>
           <span className="text-xs font-black text-gray-900 whitespace-nowrap">{Math.round(progress)}%</span>
        </div>

        <div className="flex items-center space-x-6">
          <div className="flex flex-col text-right min-w-[120px]">
            <span className="text-sm font-black text-gray-900">{formatCurrency(item.monthlyAmount)}</span>
            <span className="text-[10px] text-gray-400 font-black uppercase tracking-widest">Monthly</span>
          </div>
          <div className="flex items-center space-x-2">
            <button 
              onClick={() => { setShowViewModal(item); }}
              className="bg-gray-100 text-gray-700 px-3 py-2 rounded-xl text-xs font-black uppercase tracking-widest hover:bg-gray-200 transition-all"
            >
              View
            </button>
            <button 
              onClick={() => {
                setShowPayModal(item);
                setPayFormData({ ...payFormData, amount: item.monthlyAmount.toString() });
              }}
              className="bg-indigo-600 text-white px-4 py-2 rounded-xl text-xs font-black uppercase tracking-widest hover:bg-indigo-700 transition-all"
            >
              Pay
            </button>
            <div className="relative">
              <button 
                onClick={() => setOpenMenuId(openMenuId === item.id ? null : item.id)}
                className="p-2 text-gray-400 hover:text-gray-600 rounded-xl transition-all"
              >
                <MoreVertical className="w-5 h-5" />
              </button>
              {openMenuId === item.id && (
                <>
                  <div className="fixed inset-0 z-[10]" onClick={() => setOpenMenuId(null)}></div>
                  <div className="absolute right-0 top-full mt-2 w-44 bg-white rounded-xl shadow-xl border border-gray-100 py-2 z-[20]">
                    <button 
                      onClick={() => openEditModal(item)}
                      className="w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-50 flex items-center space-x-2"
                    >
                      <Edit2 className="w-4 h-4" />
                      <span>Edit</span>
                    </button>
                    <div className="border-t border-gray-100 my-1"></div>
                    <button 
                      onClick={() => handleDeleteTrigger(item.id, item.name)}
                      className="w-full text-left px-4 py-2 text-sm text-red-500 hover:bg-red-50 flex items-center space-x-2"
                    >
                      <Trash2 className="w-4 h-4" />
                      <span>Delete</span>
                    </button>
                  </div>
                </>
              )}
            </div>
          </div>
        </div>
      </div>
    );
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      {/* Loading State */}
      {loading && (
        <div className="flex items-center justify-center py-12">
          <div className="text-center">
            <div className="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-600 mb-4"></div>
            <p className="text-gray-600 font-medium">Loading installments from database...</p>
          </div>
        </div>
      )}

      {/* Error State */}
      {error && !loading && (
        <div className="bg-red-50 border border-red-200 rounded-xl p-4 mb-6">
          <div className="flex items-start space-x-3">
            <AlertTriangle className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
            <div>
              <h3 className="text-sm font-semibold text-red-800">Error Loading Installments</h3>
              <p className="text-sm text-red-600 mt-1">{error}</p>
            </div>
          </div>
        </div>
      )}

      {/* Main Content */}
      {!loading && (
      <>
      <div className="flex items-center justify-between">
        <div className="flex bg-gray-100 p-1 rounded-2xl">
          <button 
            onClick={() => setViewMode('card')}
            className={`p-2 rounded-xl transition-all ${viewMode === 'card' ? 'bg-white shadow-sm text-indigo-600' : 'text-gray-400'}`}
          >
            <LayoutGrid className="w-5 h-5" />
          </button>
          <button 
            onClick={() => setViewMode('list')}
            className={`p-2 rounded-xl transition-all ${viewMode === 'list' ? 'bg-white shadow-sm text-indigo-600' : 'text-gray-400'}`}
          >
            <List className="w-5 h-5" />
          </button>
        </div>
        <button 
          onClick={() => setShowModal(true)}
          className="bg-indigo-600 text-white px-8 py-3 rounded-2xl font-black uppercase tracking-widest text-xs hover:bg-indigo-700 transition-all shadow-xl shadow-indigo-100 flex items-center space-x-2"
        >
          <Plus className="w-5 h-5" />
          <span>New Installment</span>
        </button>
      </div>

      <div className={viewMode === 'card' ? "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6" : "space-y-4"}>
        {installments.length > 0 ? (
          installments.map(item => viewMode === 'card' ? renderCard(item) : renderListItem(item))
        ) : (
          <div className="col-span-full p-24 text-center">
            <p className="text-gray-400 font-black uppercase tracking-widest text-sm">No installments being tracked</p>
          </div>
        )}
      </div>
      </>
      )}

      {/* Track Modal */}
      {showModal && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/60 backdrop-blur-md">
          <div className="bg-white rounded-[2.5rem] w-full max-w-lg p-10 shadow-2xl animate-in zoom-in-95 max-h-[90vh] overflow-y-auto">
            <h2 className="text-2xl font-black text-gray-900 mb-6 uppercase tracking-tight">Track New Installment</h2>
            <form onSubmit={handleSubmit} className="space-y-6">
              <div>
                <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2">Item Name</label>
                <input required type="text" value={formData.name} onChange={(e) => setFormData({...formData, name: e.target.value})} className="w-full bg-gray-50 border-transparent rounded-2xl p-4 outline-none focus:ring-2 focus:ring-indigo-500 font-bold" placeholder="e.g. MacBook Pro" />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2">Total Amount</label>
                  <div className="relative">
                    <span className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400 font-bold">₱</span>
                    <input required type="number" value={formData.totalAmount} onChange={(e) => setFormData({...formData, totalAmount: e.target.value})} className="w-full bg-gray-50 border-transparent rounded-2xl p-4 pl-8 outline-none focus:ring-2 focus:ring-indigo-500 font-black" />
                  </div>
                </div>
                <div>
                  <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2">Monthly Payment</label>
                  <div className="relative">
                    <span className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400 font-bold">₱</span>
                    <input required type="number" value={formData.monthlyAmount} onChange={(e) => setFormData({...formData, monthlyAmount: e.target.value})} className="w-full bg-gray-50 border-transparent rounded-2xl p-4 pl-8 outline-none focus:ring-2 focus:ring-indigo-500 font-black" />
                  </div>
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2">Start Date</label>
                  <input type="month" placeholder="YYYY-MM" value={formData.startDate} onChange={(e) => setFormData({...formData, startDate: e.target.value})} className="w-full bg-gray-50 border-transparent rounded-2xl p-4 outline-none focus:ring-2 focus:ring-indigo-500 font-bold" />
                </div>
                <div>
                  <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2">Timing (PROTOTYPE)</label>
                  <select value={formData.timing} onChange={(e) => setFormData({...formData, timing: e.target.value as '1/2' | '2/2'})} className="w-full bg-gray-50 border-transparent rounded-2xl p-4 outline-none focus:ring-2 focus:ring-indigo-500 font-bold appearance-none">
                    <option value="1/2">1/2</option>
                    <option value="2/2">2/2</option>
                  </select>
                </div>
              </div>
              {/* QA: Fix for term duration issue - add term duration input field */}
              <div>
                <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2">Term Duration (months)</label>
                <input 
                  required 
                  type="number" 
                  min="1" 
                  value={formData.termDuration} 
                  onChange={(e) => setFormData({...formData, termDuration: e.target.value})} 
                  placeholder="e.g., 12, 24, 36"
                  className="w-full bg-gray-50 border-transparent rounded-2xl p-4 outline-none focus:ring-2 focus:ring-indigo-500 font-black" 
                />
              </div>
              <div>
                <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2">Already Paid</label>
                <div className="relative">
                  <span className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400 font-bold">₱</span>
                  <input required type="number" value={formData.paidAmount} onChange={(e) => setFormData({...formData, paidAmount: e.target.value})} className="w-full bg-gray-50 border-transparent rounded-2xl p-4 pl-8 outline-none focus:ring-2 focus:ring-indigo-500 font-black" />
                </div>
              </div>
              <div>
                <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2">Billing Account</label>
                <select value={formData.accountId} onChange={(e) => setFormData({...formData, accountId: e.target.value})} className="w-full bg-gray-50 border-transparent rounded-2xl p-4 outline-none focus:ring-2 focus:ring-indigo-500 font-bold appearance-none">
                   {accounts.map(acc => (
                    <option key={acc.id} value={acc.id}>{acc.bank} - {acc.classification}</option>
                  ))}
                </select>
              </div>
              {billers.filter(b => b.category.startsWith('Loans')).length > 0 && (
                <div>
                  <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2">Link to Biller (Optional - For Loans)</label>
                  <select value={formData.billerId} onChange={(e) => setFormData({...formData, billerId: e.target.value})} className="w-full bg-gray-50 border-transparent rounded-2xl p-4 outline-none focus:ring-2 focus:ring-indigo-500 font-bold appearance-none">
                    <option value="">None</option>
                    {billers.filter(b => b.category.startsWith('Loans')).map(biller => (
                      <option key={biller.id} value={biller.id}>{biller.name}</option>
                    ))}
                  </select>
                </div>
              )}
              <div className="flex space-x-4 pt-4">
                <button type="button" onClick={() => { 
                  setShowModal(false);
                  setFormData({ name: '', totalAmount: '', monthlyAmount: '', termDuration: '', paidAmount: '', accountId: accounts[0]?.id || '', startDate: '', billerId: '', timing: '1/2' });
                }} className="flex-1 bg-gray-100 py-4 rounded-2xl font-black uppercase tracking-widest text-xs text-gray-500">Cancel</button>
                <button type="submit" className="flex-1 bg-indigo-600 text-white py-4 rounded-2xl font-black uppercase tracking-widest text-xs hover:bg-indigo-700 transition-all shadow-xl">Start Tracking</button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Standardized Modals */}
      {showPayModal && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/60 backdrop-blur-md animate-in fade-in">
          <div className="bg-white rounded-3xl w-full max-w-md p-10 shadow-2xl animate-in zoom-in-95 relative">
            <button onClick={() => setShowPayModal(null)} className="absolute right-6 top-6 p-2 hover:bg-gray-100 rounded-full transition-colors">
              <X className="w-6 h-6 text-gray-400" />
            </button>
            <h2 className="text-2xl font-black text-gray-900 mb-2">Pay {showPayModal.name}</h2>
            <p className="text-gray-500 text-sm mb-8">Recording a monthly installment payment</p>
            <form onSubmit={handlePaySubmit} className="space-y-6">
              <div>
                <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2">Amount Paid</label>
                <div className="relative">
                  <span className="absolute left-4 top-1/2 -translate-y-1/2 font-bold text-gray-400">₱</span>
                  <input required type="number" value={payFormData.amount} onChange={(e) => setPayFormData({...payFormData, amount: e.target.value})} className="w-full bg-gray-50 border-transparent rounded-2xl p-4 pl-8 outline-none text-xl font-black focus:ring-2 focus:ring-indigo-500 transition-all" />
                </div>
              </div>
              
              <div>
                <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2">Receipt Upload</label>
                <div className="relative">
                  <input type="file" className="absolute inset-0 opacity-0 cursor-pointer" onChange={(e) => setPayFormData({...payFormData, receipt: e.target.files?.[0]?.name || ''})} />
                  <div className="w-full bg-gray-50 border-2 border-dashed border-gray-200 rounded-2xl p-6 text-center text-sm text-gray-500 hover:border-indigo-300 hover:bg-indigo-50 transition-all flex flex-col items-center">
                    <Upload className="w-8 h-8 mb-2 text-indigo-400" />
                    <span className="font-bold">{payFormData.receipt || 'Click or drag to upload receipt'}</span>
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2">Date Paid</label>
                  <input required type="date" value={payFormData.datePaid} onChange={(e) => setPayFormData({...payFormData, datePaid: e.target.value})} className="w-full bg-gray-50 border-transparent rounded-2xl p-4 outline-none font-bold text-sm" />
                </div>
                <div>
                  <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2">Payment Method</label>
                  <select value={payFormData.accountId} onChange={(e) => setPayFormData({...payFormData, accountId: e.target.value})} className="w-full bg-gray-50 border-transparent rounded-2xl p-4 outline-none font-bold text-sm appearance-none">
                    {accounts.filter(acc => acc.classification !== 'Credit Card' && acc.type !== 'Credit').map(acc => <option key={acc.id} value={acc.id}>{acc.bank} ({acc.classification})</option>)}
                  </select>
                </div>
              </div>

              <div className="flex space-x-4 pt-4">
                <button type="button" onClick={() => setShowPayModal(null)} className="flex-1 bg-gray-100 py-4 rounded-2xl font-bold text-gray-500 hover:bg-gray-200 transition-colors">Cancel</button>
                <button type="submit" className="flex-1 bg-green-600 text-white py-4 rounded-2xl font-bold hover:bg-green-700 shadow-xl shadow-green-100 transition-all active:scale-95">Record Payment</button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Edit Modal */}
      {showEditModal && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/60 backdrop-blur-md">
          <div className="bg-white rounded-[2.5rem] w-full max-w-lg p-10 shadow-2xl animate-in zoom-in-95 max-h-[90vh] overflow-y-auto">
            <h2 className="text-2xl font-black text-gray-900 mb-6 uppercase tracking-tight">Edit Installment</h2>
            <form onSubmit={handleEditSubmit} className="space-y-6">
              <div>
                <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2">Item Name</label>
                <input required type="text" value={editFormData.name} onChange={(e) => setEditFormData({...editFormData, name: e.target.value})} className="w-full bg-gray-50 border-transparent rounded-2xl p-4 outline-none focus:ring-2 focus:ring-indigo-500 font-bold" />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2">Total Amount</label>
                  <div className="relative">
                    <span className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400 font-bold">₱</span>
                    <input required type="number" value={editFormData.totalAmount} onChange={(e) => setEditFormData({...editFormData, totalAmount: e.target.value})} className="w-full bg-gray-50 border-transparent rounded-2xl p-4 pl-8 outline-none focus:ring-2 focus:ring-indigo-500 font-black" />
                  </div>
                </div>
                <div>
                  <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2">Monthly Payment</label>
                  <div className="relative">
                    <span className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400 font-bold">₱</span>
                    <input required type="number" value={editFormData.monthlyAmount} onChange={(e) => setEditFormData({...editFormData, monthlyAmount: e.target.value})} className="w-full bg-gray-50 border-transparent rounded-2xl p-4 pl-8 outline-none focus:ring-2 focus:ring-indigo-500 font-black" />
                  </div>
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2">Start Date</label>
                  <input type="month" value={editFormData.startDate} onChange={(e) => setEditFormData({...editFormData, startDate: e.target.value})} className="w-full bg-gray-50 border-transparent rounded-2xl p-4 outline-none focus:ring-2 focus:ring-indigo-500 font-bold" />
                </div>
                <div>
                  <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2">Timing (PROTOTYPE)</label>
                  <select value={editFormData.timing} onChange={(e) => setEditFormData({...editFormData, timing: e.target.value as '1/2' | '2/2'})} className="w-full bg-gray-50 border-transparent rounded-2xl p-4 outline-none focus:ring-2 focus:ring-indigo-500 font-bold appearance-none">
                    <option value="1/2">1/2</option>
                    <option value="2/2">2/2</option>
                  </select>
                </div>
              </div>
              {/* QA: Fix for term duration issue - add term duration input field */}
              <div>
                <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2">Term Duration (months)</label>
                <input 
                  required 
                  type="number" 
                  min="1" 
                  value={editFormData.termDuration} 
                  onChange={(e) => setEditFormData({...editFormData, termDuration: e.target.value})} 
                  placeholder="e.g., 12, 24, 36"
                  className="w-full bg-gray-50 border-transparent rounded-2xl p-4 outline-none focus:ring-2 focus:ring-indigo-500 font-black" 
                />
              </div>
              <div>
                <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2">Already Paid</label>
                <div className="relative">
                  <span className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400 font-bold">₱</span>
                  <input required type="number" value={editFormData.paidAmount} onChange={(e) => setEditFormData({...editFormData, paidAmount: e.target.value})} className="w-full bg-gray-50 border-transparent rounded-2xl p-4 pl-8 outline-none focus:ring-2 focus:ring-indigo-500 font-black" />
                </div>
              </div>
              <div>
                <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2">Billing Account</label>
                <select value={editFormData.accountId} onChange={(e) => setEditFormData({...editFormData, accountId: e.target.value})} className="w-full bg-gray-50 border-transparent rounded-2xl p-4 outline-none focus:ring-2 focus:ring-indigo-500 font-bold appearance-none">
                   {accounts.map(acc => (
                    <option key={acc.id} value={acc.id}>{acc.bank} - {acc.classification}</option>
                  ))}
                </select>
              </div>
              {billers.filter(b => b.category.startsWith('Loans')).length > 0 && (
                <div>
                  <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2">Link to Biller (Optional - For Loans)</label>
                  <select value={editFormData.billerId} onChange={(e) => setEditFormData({...editFormData, billerId: e.target.value})} className="w-full bg-gray-50 border-transparent rounded-2xl p-4 outline-none focus:ring-2 focus:ring-indigo-500 font-bold appearance-none">
                    <option value="">None</option>
                    {billers.filter(b => b.category.startsWith('Loans')).map(biller => (
                      <option key={biller.id} value={biller.id}>{biller.name}</option>
                    ))}
                  </select>
                </div>
              )}
              <div className="flex space-x-4 pt-4">
                <button type="button" onClick={() => setShowEditModal(null)} className="flex-1 bg-gray-100 py-4 rounded-2xl font-black uppercase tracking-widest text-xs text-gray-500">Cancel</button>
                <button type="submit" className="flex-1 bg-indigo-600 text-white py-4 rounded-2xl font-black uppercase tracking-widest text-xs hover:bg-indigo-700 transition-all shadow-xl">Save Changes</button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* View Schedule Modal */}
      {showViewModal && (() => {
        const generateMonthlySchedule = () => {
          if (!showViewModal.startDate) return [];
          
          const [startYear, startMonth] = showViewModal.startDate.split('-').map(Number);
          const termMonths = parseInt(showViewModal.termDuration) || 12;
          const monthlyAmount = showViewModal.monthlyAmount;
          const schedule = [];
          
          for (let i = 0; i < termMonths; i++) {
            const monthIndex = (startMonth - 1 + i) % 12;
            const year = startYear + Math.floor((startMonth - 1 + i) / 12);
            const monthName = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'][monthIndex];
            
            schedule.push({
              month: `${monthName} ${year}`,
              amount: monthlyAmount,
              isPaid: (i + 1) * monthlyAmount <= showViewModal.paidAmount
            });
          }
          
          return schedule;
        };
        
        const schedule = generateMonthlySchedule();
        
        return (
          <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/60 backdrop-blur-md">
            <div className="bg-white rounded-[2.5rem] w-full max-w-3xl p-10 shadow-2xl animate-in zoom-in-95 max-h-[90vh] overflow-y-auto">
              <div className="flex items-center justify-between mb-6">
                <div>
                  <h2 className="text-2xl font-black text-gray-900 uppercase tracking-tight">{showViewModal.name}</h2>
                  <p className="text-gray-500 text-sm mt-1">Monthly Payment Schedule</p>
                </div>
                <button onClick={() => setShowViewModal(null)} className="p-2 hover:bg-gray-100 rounded-full transition-colors">
                  <X className="w-6 h-6 text-gray-400" />
                </button>
              </div>
              
              <div className="bg-gray-50 rounded-2xl p-6 mb-6 grid grid-cols-3 gap-4">
                <div>
                  <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">Total Amount</p>
                  <p className="text-lg font-black text-gray-900">{formatCurrency(showViewModal.totalAmount)}</p>
                </div>
                <div>
                  <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">Paid Amount</p>
                  <p className="text-lg font-black text-green-600">{formatCurrency(showViewModal.paidAmount)}</p>
                </div>
                <div>
                  <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">Remaining</p>
                  <p className="text-lg font-black text-gray-900">{formatCurrency(showViewModal.totalAmount - showViewModal.paidAmount)}</p>
                </div>
              </div>
              
              {schedule.length > 0 ? (
                <div className="space-y-2">
                  <h3 className="text-sm font-black text-gray-400 uppercase tracking-widest mb-4">Payment Schedule</h3>
                  {schedule.map((item, index) => (
                    <div key={index} className={`flex items-center justify-between p-4 rounded-xl border transition-all ${item.isPaid ? 'bg-green-50 border-green-200' : 'bg-white border-gray-100 hover:bg-gray-50'}`}>
                      <div className="flex items-center space-x-4">
                        <span className={`text-sm font-black ${item.isPaid ? 'text-green-600' : 'text-gray-900'}`}>{item.month}</span>
                        {item.isPaid && (
                          <span className="text-[10px] font-bold px-2 py-0.5 bg-green-100 text-green-700 rounded uppercase">Paid</span>
                        )}
                      </div>
                      <div className="flex items-center space-x-4">
                        <span className="font-black text-gray-900">{formatCurrency(item.amount)}</span>
                        {!item.isPaid && (
                          <button 
                            onClick={() => {
                              setShowViewModal(null);
                              setShowPayModal(showViewModal);
                              setPayFormData({ ...payFormData, amount: showViewModal.monthlyAmount.toString() });
                            }}
                            className="bg-indigo-600 text-white px-4 py-2 rounded-xl text-xs font-black uppercase tracking-widest hover:bg-indigo-700 transition-all"
                          >
                            Pay
                          </button>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="text-center py-12">
                  <p className="text-gray-400 font-bold">No start date set. Please edit the installment to add a start date.</p>
                </div>
              )}
            </div>
          </div>
        );
      })()}

      {confirmModal.show && <ConfirmDialog {...confirmModal} onClose={() => setConfirmModal(p => ({ ...p, show: false }))} />}
    </div>
  );
};

const ConfirmDialog: React.FC<{ show: boolean; title: string; message: string; onConfirm: () => void; onClose: () => void }> = ({ title, message, onConfirm, onClose }) => (
  <div className="fixed inset-0 z-[200] flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm animate-in fade-in">
    <div className="bg-white rounded-[2.5rem] w-full max-w-sm p-10 shadow-2xl animate-in zoom-in-95 flex flex-col items-center text-center">
      <div className="w-16 h-16 bg-red-50 text-red-600 rounded-3xl flex items-center justify-center mb-6">
        <AlertTriangle className="w-8 h-8" />
      </div>
      <h3 className="text-xl font-black text-gray-900 mb-2 uppercase tracking-tight">{title}</h3>
      <p className="text-sm text-gray-500 mb-8 font-medium leading-relaxed">{message}</p>
      <div className="flex flex-col w-full space-y-3">
        <button onClick={onConfirm} className="w-full bg-red-600 text-white py-4 rounded-2xl font-black uppercase tracking-widest text-[10px] hover:bg-red-700 transition-all shadow-lg shadow-red-100">
          Proceed
        </button>
        <button onClick={onClose} className="w-full bg-gray-100 text-gray-500 py-4 rounded-2xl font-black uppercase tracking-widest text-[10px] hover:bg-gray-200 transition-all">
          Cancel
        </button>
      </div>
    </div>
  </div>
);

export default Installments;